/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type {
  AuthTokenSettings,
  AwsCreditAccountEntity,
  DataSinkConfig,
  DeveloperCredit,
  FipsSettings,
  Invoice,
  LoginBannerSettings,
  Macros,
  RateConfig,
  TenantAddressPatch,
  TenantAssetCert,
  TenantAssetCerts,
  TenantClusterSettings,
  TenantDomains,
  TenantEmailPatch,
  TenantEnableClusterGroup,
  TenantFreemium,
  TenantFreemiumUsage,
  TenantOidcClientSpec,
  TenantPasswordPolicyEntity,
  TenantResourceLimits,
  TenantResourceLimitsEntity,
  TenantSamlRequestSpec,
  TenantSamlSpec,
  TenantSsoAuthProvidersEntity,
  TenantsCreditAccountDeleteParams,
  Uid,
  V1DataSinkConfigBody,
  V1MacrosBody,
  V1NodesAutoRemediationSettingsBody,
  V1TenantAssetCertBody,
} from ".././schemas";

import { customInstance } from ".././httpClient/customClient";

/**
 * @summary Update tenant address
 */
export type patchTenantAddressResponse204 = {
  data: void;
  status: 204;
};

export type patchTenantAddressResponseComposite = patchTenantAddressResponse204;

export type patchTenantAddressResponse = patchTenantAddressResponseComposite & {
  headers: Headers;
};

export const getPatchTenantAddressUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/address`;
};

export const patchTenantAddress = async (
  tenantUid: string,
  tenantAddressPatch: TenantAddressPatch,
  options?: RequestInit,
): Promise<patchTenantAddressResponse> => {
  return customInstance<patchTenantAddressResponse>(
    getPatchTenantAddressUrl(tenantUid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(tenantAddressPatch),
    },
  );
};

/**
 * @summary lists the certificates for the tenant
 */
export type v1TenantUIdAssetsCertsListResponse200 = {
  data: TenantAssetCerts;
  status: 200;
};

export type v1TenantUIdAssetsCertsListResponseComposite =
  v1TenantUIdAssetsCertsListResponse200;

export type v1TenantUIdAssetsCertsListResponse =
  v1TenantUIdAssetsCertsListResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUIdAssetsCertsListUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/assets/certs`;
};

export const v1TenantUIdAssetsCertsList = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<v1TenantUIdAssetsCertsListResponse> => {
  return customInstance<v1TenantUIdAssetsCertsListResponse>(
    getV1TenantUIdAssetsCertsListUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary create the tenant certificate
 */
export type v1TenantUidAssetsCertsCreateResponse201 = {
  data: Uid;
  status: 201;
};

export type v1TenantUidAssetsCertsCreateResponseComposite =
  v1TenantUidAssetsCertsCreateResponse201;

export type v1TenantUidAssetsCertsCreateResponse =
  v1TenantUidAssetsCertsCreateResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidAssetsCertsCreateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/assets/certs`;
};

export const v1TenantUidAssetsCertsCreate = async (
  tenantUid: string,
  v1TenantAssetCertBody: V1TenantAssetCertBody,
  options?: RequestInit,
): Promise<v1TenantUidAssetsCertsCreateResponse> => {
  return customInstance<v1TenantUidAssetsCertsCreateResponse>(
    getV1TenantUidAssetsCertsCreateUrl(tenantUid),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1TenantAssetCertBody),
    },
  );
};

/**
 * @summary deletes the tenant certificate
 */
export type v1TenantUidAssetsCertsUidDeleteResponse204 = {
  data: void;
  status: 204;
};

export type v1TenantUidAssetsCertsUidDeleteResponseComposite =
  v1TenantUidAssetsCertsUidDeleteResponse204;

export type v1TenantUidAssetsCertsUidDeleteResponse =
  v1TenantUidAssetsCertsUidDeleteResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidAssetsCertsUidDeleteUrl = (
  tenantUid: string,
  certificateUid: string,
) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/assets/certs/${certificateUid}`;
};

export const v1TenantUidAssetsCertsUidDelete = async (
  tenantUid: string,
  certificateUid: string,
  options?: RequestInit,
): Promise<v1TenantUidAssetsCertsUidDeleteResponse> => {
  return customInstance<v1TenantUidAssetsCertsUidDeleteResponse>(
    getV1TenantUidAssetsCertsUidDeleteUrl(tenantUid, certificateUid),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Returns the ca certificate for the tenant
 */
export type v1TenantUidAssetsCertsUidGetResponse200 = {
  data: TenantAssetCert;
  status: 200;
};

export type v1TenantUidAssetsCertsUidGetResponseComposite =
  v1TenantUidAssetsCertsUidGetResponse200;

export type v1TenantUidAssetsCertsUidGetResponse =
  v1TenantUidAssetsCertsUidGetResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidAssetsCertsUidGetUrl = (
  tenantUid: string,
  certificateUid: string,
) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/assets/certs/${certificateUid}`;
};

export const v1TenantUidAssetsCertsUidGet = async (
  tenantUid: string,
  certificateUid: string,
  options?: RequestInit,
): Promise<v1TenantUidAssetsCertsUidGetResponse> => {
  return customInstance<v1TenantUidAssetsCertsUidGetResponse>(
    getV1TenantUidAssetsCertsUidGetUrl(tenantUid, certificateUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary updates the tenant certificate
 */
export type v1TenantUidAssetsCertsUidUpdateResponse204 = {
  data: void;
  status: 204;
};

export type v1TenantUidAssetsCertsUidUpdateResponseComposite =
  v1TenantUidAssetsCertsUidUpdateResponse204;

export type v1TenantUidAssetsCertsUidUpdateResponse =
  v1TenantUidAssetsCertsUidUpdateResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidAssetsCertsUidUpdateUrl = (
  tenantUid: string,
  certificateUid: string,
) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/assets/certs/${certificateUid}`;
};

export const v1TenantUidAssetsCertsUidUpdate = async (
  tenantUid: string,
  certificateUid: string,
  v1TenantAssetCertBody: V1TenantAssetCertBody,
  options?: RequestInit,
): Promise<v1TenantUidAssetsCertsUidUpdateResponse> => {
  return customInstance<v1TenantUidAssetsCertsUidUpdateResponse>(
    getV1TenantUidAssetsCertsUidUpdateUrl(tenantUid, certificateUid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1TenantAssetCertBody),
    },
  );
};

/**
 * @summary deletes the tenant data sink config
 */
export type v1TenantUidAssetsDataSinksDeleteResponse204 = {
  data: void;
  status: 204;
};

export type v1TenantUidAssetsDataSinksDeleteResponseComposite =
  v1TenantUidAssetsDataSinksDeleteResponse204;

export type v1TenantUidAssetsDataSinksDeleteResponse =
  v1TenantUidAssetsDataSinksDeleteResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidAssetsDataSinksDeleteUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/assets/dataSinks`;
};

export const v1TenantUidAssetsDataSinksDelete = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<v1TenantUidAssetsDataSinksDeleteResponse> => {
  return customInstance<v1TenantUidAssetsDataSinksDeleteResponse>(
    getV1TenantUidAssetsDataSinksDeleteUrl(tenantUid),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Returns data sink config of tenant
 */
export type v1TenantUidAssetsDataSinksGetResponse200 = {
  data: DataSinkConfig;
  status: 200;
};

export type v1TenantUidAssetsDataSinksGetResponseComposite =
  v1TenantUidAssetsDataSinksGetResponse200;

export type v1TenantUidAssetsDataSinksGetResponse =
  v1TenantUidAssetsDataSinksGetResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidAssetsDataSinksGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/assets/dataSinks`;
};

export const v1TenantUidAssetsDataSinksGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<v1TenantUidAssetsDataSinksGetResponse> => {
  return customInstance<v1TenantUidAssetsDataSinksGetResponse>(
    getV1TenantUidAssetsDataSinksGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary create data sink config
 */
export type v1TenantUidAssetsDataSinksCreateResponse201 = {
  data: Uid;
  status: 201;
};

export type v1TenantUidAssetsDataSinksCreateResponseComposite =
  v1TenantUidAssetsDataSinksCreateResponse201;

export type v1TenantUidAssetsDataSinksCreateResponse =
  v1TenantUidAssetsDataSinksCreateResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidAssetsDataSinksCreateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/assets/dataSinks`;
};

export const v1TenantUidAssetsDataSinksCreate = async (
  tenantUid: string,
  v1DataSinkConfigBody: V1DataSinkConfigBody,
  options?: RequestInit,
): Promise<v1TenantUidAssetsDataSinksCreateResponse> => {
  return customInstance<v1TenantUidAssetsDataSinksCreateResponse>(
    getV1TenantUidAssetsDataSinksCreateUrl(tenantUid),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1DataSinkConfigBody),
    },
  );
};

/**
 * @summary updates the tenant data sink config
 */
export type v1TenantUidAssetsDataSinksUpdateResponse204 = {
  data: void;
  status: 204;
};

export type v1TenantUidAssetsDataSinksUpdateResponseComposite =
  v1TenantUidAssetsDataSinksUpdateResponse204;

export type v1TenantUidAssetsDataSinksUpdateResponse =
  v1TenantUidAssetsDataSinksUpdateResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidAssetsDataSinksUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/assets/dataSinks`;
};

export const v1TenantUidAssetsDataSinksUpdate = async (
  tenantUid: string,
  v1DataSinkConfigBody: V1DataSinkConfigBody,
  options?: RequestInit,
): Promise<v1TenantUidAssetsDataSinksUpdateResponse> => {
  return customInstance<v1TenantUidAssetsDataSinksUpdateResponse>(
    getV1TenantUidAssetsDataSinksUpdateUrl(tenantUid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1DataSinkConfigBody),
    },
  );
};

/**
 * @summary Get tenant auth token settings
 */
export type tenantUidAuthTokenSettingsGetResponse200 = {
  data: AuthTokenSettings;
  status: 200;
};

export type tenantUidAuthTokenSettingsGetResponseComposite =
  tenantUidAuthTokenSettingsGetResponse200;

export type tenantUidAuthTokenSettingsGetResponse =
  tenantUidAuthTokenSettingsGetResponseComposite & {
    headers: Headers;
  };

export const getTenantUidAuthTokenSettingsGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/authTokenSettings`;
};

export const tenantUidAuthTokenSettingsGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<tenantUidAuthTokenSettingsGetResponse> => {
  return customInstance<tenantUidAuthTokenSettingsGetResponse>(
    getTenantUidAuthTokenSettingsGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update tenant auth token settings
 */
export type tenantUidAuthTokenSettingsUpdateResponse204 = {
  data: void;
  status: 204;
};

export type tenantUidAuthTokenSettingsUpdateResponseComposite =
  tenantUidAuthTokenSettingsUpdateResponse204;

export type tenantUidAuthTokenSettingsUpdateResponse =
  tenantUidAuthTokenSettingsUpdateResponseComposite & {
    headers: Headers;
  };

export const getTenantUidAuthTokenSettingsUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/authTokenSettings`;
};

export const tenantUidAuthTokenSettingsUpdate = async (
  tenantUid: string,
  authTokenSettings: AuthTokenSettings,
  options?: RequestInit,
): Promise<tenantUidAuthTokenSettingsUpdateResponse> => {
  return customInstance<tenantUidAuthTokenSettingsUpdateResponse>(
    getTenantUidAuthTokenSettingsUpdateUrl(tenantUid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(authTokenSettings),
    },
  );
};

/**
 * @summary Tenant to accept the contract agreement
 */
export type tenantsUidContractAcceptResponse204 = {
  data: void;
  status: 204;
};

export type tenantsUidContractAcceptResponseComposite =
  tenantsUidContractAcceptResponse204;

export type tenantsUidContractAcceptResponse =
  tenantsUidContractAcceptResponseComposite & {
    headers: Headers;
  };

export const getTenantsUidContractAcceptUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/contract/accept`;
};

export const tenantsUidContractAccept = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<tenantsUidContractAcceptResponse> => {
  return customInstance<tenantsUidContractAcceptResponse>(
    getTenantsUidContractAcceptUrl(tenantUid),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * @summary Deletes the aws credit account for tenants
 */
export type tenantsCreditAccountDeleteResponse204 = {
  data: void;
  status: 204;
};

export type tenantsCreditAccountDeleteResponseComposite =
  tenantsCreditAccountDeleteResponse204;

export type tenantsCreditAccountDeleteResponse =
  tenantsCreditAccountDeleteResponseComposite & {
    headers: Headers;
  };

export const getTenantsCreditAccountDeleteUrl = (
  tenantUid: string,
  params?: TenantsCreditAccountDeleteParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.spectrocloud.com/v1/tenants/${tenantUid}/creditAccount/aws?${stringifiedParams}`
    : `https://api.spectrocloud.com/v1/tenants/${tenantUid}/creditAccount/aws`;
};

export const tenantsCreditAccountDelete = async (
  tenantUid: string,
  params?: TenantsCreditAccountDeleteParams,
  options?: RequestInit,
): Promise<tenantsCreditAccountDeleteResponse> => {
  return customInstance<tenantsCreditAccountDeleteResponse>(
    getTenantsCreditAccountDeleteUrl(tenantUid, params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get the credit accounts for the tenants with free tier access
 */
export type tenantsCreditAccountGetResponse200 = {
  data: AwsCreditAccountEntity;
  status: 200;
};

export type tenantsCreditAccountGetResponseComposite =
  tenantsCreditAccountGetResponse200;

export type tenantsCreditAccountGetResponse =
  tenantsCreditAccountGetResponseComposite & {
    headers: Headers;
  };

export const getTenantsCreditAccountGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/creditAccount/aws`;
};

export const tenantsCreditAccountGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<tenantsCreditAccountGetResponse> => {
  return customInstance<tenantsCreditAccountGetResponse>(
    getTenantsCreditAccountGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary retrieves the domains for tenant
 */
export type v1TenantUidDomainsGetResponse200 = {
  data: TenantDomains;
  status: 200;
};

export type v1TenantUidDomainsGetResponseComposite =
  v1TenantUidDomainsGetResponse200;

export type v1TenantUidDomainsGetResponse =
  v1TenantUidDomainsGetResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidDomainsGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/domains`;
};

export const v1TenantUidDomainsGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<v1TenantUidDomainsGetResponse> => {
  return customInstance<v1TenantUidDomainsGetResponse>(
    getV1TenantUidDomainsGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary creates or updates domains for tenant
 */
export type v1TenantUidDomainsUpdateResponse204 = {
  data: void;
  status: 204;
};

export type v1TenantUidDomainsUpdateResponseComposite =
  v1TenantUidDomainsUpdateResponse204;

export type v1TenantUidDomainsUpdateResponse =
  v1TenantUidDomainsUpdateResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidDomainsUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/domains`;
};

export const v1TenantUidDomainsUpdate = async (
  tenantUid: string,
  tenantDomains: TenantDomains,
  options?: RequestInit,
): Promise<v1TenantUidDomainsUpdateResponse> => {
  return customInstance<v1TenantUidDomainsUpdateResponse>(
    getV1TenantUidDomainsUpdateUrl(tenantUid),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(tenantDomains),
    },
  );
};

/**
 * @summary Update tenant emailId
 */
export type patchTenantEmailIdResponse204 = {
  data: void;
  status: 204;
};

export type patchTenantEmailIdResponseComposite = patchTenantEmailIdResponse204;

export type patchTenantEmailIdResponse = patchTenantEmailIdResponseComposite & {
  headers: Headers;
};

export const getPatchTenantEmailIdUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/emailId`;
};

export const patchTenantEmailId = async (
  tenantUid: string,
  tenantEmailPatch: TenantEmailPatch,
  options?: RequestInit,
): Promise<patchTenantEmailIdResponse> => {
  return customInstance<patchTenantEmailIdResponse>(
    getPatchTenantEmailIdUrl(tenantUid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(tenantEmailPatch),
    },
  );
};

/**
 * @summary Get tenant level freemium configuration
 */
export type tenantFreemiumGetResponse200 = {
  data: TenantFreemium;
  status: 200;
};

export type tenantFreemiumGetResponseComposite = tenantFreemiumGetResponse200;

export type tenantFreemiumGetResponse = tenantFreemiumGetResponseComposite & {
  headers: Headers;
};

export const getTenantFreemiumGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/freemium`;
};

export const tenantFreemiumGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<tenantFreemiumGetResponse> => {
  return customInstance<tenantFreemiumGetResponse>(
    getTenantFreemiumGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update tenant freemium configuration
 */
export type tenantFreemiumUpdateResponse204 = {
  data: void;
  status: 204;
};

export type tenantFreemiumUpdateResponseComposite =
  tenantFreemiumUpdateResponse204;

export type tenantFreemiumUpdateResponse =
  tenantFreemiumUpdateResponseComposite & {
    headers: Headers;
  };

export const getTenantFreemiumUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/freemium`;
};

export const tenantFreemiumUpdate = async (
  tenantUid: string,
  tenantFreemium: TenantFreemium,
  options?: RequestInit,
): Promise<tenantFreemiumUpdateResponse> => {
  return customInstance<tenantFreemiumUpdateResponse>(
    getTenantFreemiumUpdateUrl(tenantUid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(tenantFreemium),
    },
  );
};

/**
 * @summary Get tenant freemium usage
 */
export type tenantFreemiumUsageGetResponse200 = {
  data: TenantFreemiumUsage;
  status: 200;
};

export type tenantFreemiumUsageGetResponseComposite =
  tenantFreemiumUsageGetResponse200;

export type tenantFreemiumUsageGetResponse =
  tenantFreemiumUsageGetResponseComposite & {
    headers: Headers;
  };

export const getTenantFreemiumUsageGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/freemiumUsage`;
};

export const tenantFreemiumUsageGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<tenantFreemiumUsageGetResponse> => {
  return customInstance<tenantFreemiumUsageGetResponse>(
    getTenantFreemiumUsageGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Returns a specified invoice
 */
export type invoicesUidGetResponse200 = {
  data: Invoice;
  status: 200;
};

export type invoicesUidGetResponseComposite = invoicesUidGetResponse200;

export type invoicesUidGetResponse = invoicesUidGetResponseComposite & {
  headers: Headers;
};

export const getInvoicesUidGetUrl = (tenantUid: string, invoiceUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/invoices/${invoiceUid}`;
};

export const invoicesUidGet = async (
  tenantUid: string,
  invoiceUid: string,
  options?: RequestInit,
): Promise<invoicesUidGetResponse> => {
  return customInstance<invoicesUidGetResponse>(
    getInvoicesUidGetUrl(tenantUid, invoiceUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Downloads the specified invoice report
 */
export type v1InvoiceUidReportInvoicePdfResponse200 = {
  data: Blob;
  status: 200;
};

export type v1InvoiceUidReportInvoicePdfResponseComposite =
  v1InvoiceUidReportInvoicePdfResponse200;

export type v1InvoiceUidReportInvoicePdfResponse =
  v1InvoiceUidReportInvoicePdfResponseComposite & {
    headers: Headers;
  };

export const getV1InvoiceUidReportInvoicePdfUrl = (
  tenantUid: string,
  invoiceUid: string,
) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/invoices/${invoiceUid}/report/invoice/pdf`;
};

export const v1InvoiceUidReportInvoicePdf = async (
  tenantUid: string,
  invoiceUid: string,
  options?: RequestInit,
): Promise<v1InvoiceUidReportInvoicePdfResponse> => {
  return customInstance<v1InvoiceUidReportInvoicePdfResponse>(
    getV1InvoiceUidReportInvoicePdfUrl(tenantUid, invoiceUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Downloads the specified monthly invoice report
 */
export type v1InvoiceUidReportPdfResponse200 = {
  data: Blob;
  status: 200;
};

export type v1InvoiceUidReportPdfResponseComposite =
  v1InvoiceUidReportPdfResponse200;

export type v1InvoiceUidReportPdfResponse =
  v1InvoiceUidReportPdfResponseComposite & {
    headers: Headers;
  };

export const getV1InvoiceUidReportPdfUrl = (
  tenantUid: string,
  invoiceUid: string,
) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/invoices/${invoiceUid}/report/pdf`;
};

export const v1InvoiceUidReportPdf = async (
  tenantUid: string,
  invoiceUid: string,
  options?: RequestInit,
): Promise<v1InvoiceUidReportPdfResponse> => {
  return customInstance<v1InvoiceUidReportPdfResponse>(
    getV1InvoiceUidReportPdfUrl(tenantUid, invoiceUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Downloads the specified tenant usage
 */
export type v1InvoiceUidReportUsagePdfResponse200 = {
  data: Blob;
  status: 200;
};

export type v1InvoiceUidReportUsagePdfResponseComposite =
  v1InvoiceUidReportUsagePdfResponse200;

export type v1InvoiceUidReportUsagePdfResponse =
  v1InvoiceUidReportUsagePdfResponseComposite & {
    headers: Headers;
  };

export const getV1InvoiceUidReportUsagePdfUrl = (
  tenantUid: string,
  invoiceUid: string,
) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/invoices/${invoiceUid}/report/usage/pdf`;
};

export const v1InvoiceUidReportUsagePdf = async (
  tenantUid: string,
  invoiceUid: string,
  options?: RequestInit,
): Promise<v1InvoiceUidReportUsagePdfResponse> => {
  return customInstance<v1InvoiceUidReportUsagePdfResponse>(
    getV1InvoiceUidReportUsagePdfUrl(tenantUid, invoiceUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get tenant login banner settings
 */
export type tenantUidLoginBannerGetResponse200 = {
  data: LoginBannerSettings;
  status: 200;
};

export type tenantUidLoginBannerGetResponseComposite =
  tenantUidLoginBannerGetResponse200;

export type tenantUidLoginBannerGetResponse =
  tenantUidLoginBannerGetResponseComposite & {
    headers: Headers;
  };

export const getTenantUidLoginBannerGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/loginBanner`;
};

export const tenantUidLoginBannerGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<tenantUidLoginBannerGetResponse> => {
  return customInstance<tenantUidLoginBannerGetResponse>(
    getTenantUidLoginBannerGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update tenant login banner settings
 */
export type tenantUidLoginBannerUpdateResponse204 = {
  data: void;
  status: 204;
};

export type tenantUidLoginBannerUpdateResponseComposite =
  tenantUidLoginBannerUpdateResponse204;

export type tenantUidLoginBannerUpdateResponse =
  tenantUidLoginBannerUpdateResponseComposite & {
    headers: Headers;
  };

export const getTenantUidLoginBannerUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/loginBanner`;
};

export const tenantUidLoginBannerUpdate = async (
  tenantUid: string,
  loginBannerSettings: LoginBannerSettings,
  options?: RequestInit,
): Promise<tenantUidLoginBannerUpdateResponse> => {
  return customInstance<tenantUidLoginBannerUpdateResponse>(
    getTenantUidLoginBannerUpdateUrl(tenantUid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(loginBannerSettings),
    },
  );
};

/**
 * @summary Delete the macros for the specified tenant by given macro name
 */
export type tenantsUidMacrosDeleteByMacroNameResponse204 = {
  data: void;
  status: 204;
};

export type tenantsUidMacrosDeleteByMacroNameResponseComposite =
  tenantsUidMacrosDeleteByMacroNameResponse204;

export type tenantsUidMacrosDeleteByMacroNameResponse =
  tenantsUidMacrosDeleteByMacroNameResponseComposite & {
    headers: Headers;
  };

export const getTenantsUidMacrosDeleteByMacroNameUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/macros`;
};

export const tenantsUidMacrosDeleteByMacroName = async (
  tenantUid: string,
  v1MacrosBody: V1MacrosBody,
  options?: RequestInit,
): Promise<tenantsUidMacrosDeleteByMacroNameResponse> => {
  return customInstance<tenantsUidMacrosDeleteByMacroNameResponse>(
    getTenantsUidMacrosDeleteByMacroNameUrl(tenantUid),
    {
      ...options,
      method: "DELETE",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1MacrosBody),
    },
  );
};

/**
 * @summary List the macros of the specified tenant
 */
export type tenantsUidMacrosListResponse200 = {
  data: Macros;
  status: 200;
};

export type tenantsUidMacrosListResponseComposite =
  tenantsUidMacrosListResponse200;

export type tenantsUidMacrosListResponse =
  tenantsUidMacrosListResponseComposite & {
    headers: Headers;
  };

export const getTenantsUidMacrosListUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/macros`;
};

export const tenantsUidMacrosList = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<tenantsUidMacrosListResponse> => {
  return customInstance<tenantsUidMacrosListResponse>(
    getTenantsUidMacrosListUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update the macros for the specified tenant by given macro name
 */
export type tenantsUidMacrosUpdateByMacroNameResponse204 = {
  data: void;
  status: 204;
};

export type tenantsUidMacrosUpdateByMacroNameResponseComposite =
  tenantsUidMacrosUpdateByMacroNameResponse204;

export type tenantsUidMacrosUpdateByMacroNameResponse =
  tenantsUidMacrosUpdateByMacroNameResponseComposite & {
    headers: Headers;
  };

export const getTenantsUidMacrosUpdateByMacroNameUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/macros`;
};

export const tenantsUidMacrosUpdateByMacroName = async (
  tenantUid: string,
  v1MacrosBody: V1MacrosBody,
  options?: RequestInit,
): Promise<tenantsUidMacrosUpdateByMacroNameResponse> => {
  return customInstance<tenantsUidMacrosUpdateByMacroNameResponse>(
    getTenantsUidMacrosUpdateByMacroNameUrl(tenantUid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1MacrosBody),
    },
  );
};

/**
 * @summary Create or add new macros for the specified tenant
 */
export type tenantsUidMacrosCreateResponse204 = {
  data: void;
  status: 204;
};

export type tenantsUidMacrosCreateResponseComposite =
  tenantsUidMacrosCreateResponse204;

export type tenantsUidMacrosCreateResponse =
  tenantsUidMacrosCreateResponseComposite & {
    headers: Headers;
  };

export const getTenantsUidMacrosCreateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/macros`;
};

export const tenantsUidMacrosCreate = async (
  tenantUid: string,
  v1MacrosBody: V1MacrosBody,
  options?: RequestInit,
): Promise<tenantsUidMacrosCreateResponse> => {
  return customInstance<tenantsUidMacrosCreateResponse>(
    getTenantsUidMacrosCreateUrl(tenantUid),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1MacrosBody),
    },
  );
};

/**
 * @summary Update the macros of the specified tenant
 */
export type tenantsUidMacrosUpdateResponse204 = {
  data: void;
  status: 204;
};

export type tenantsUidMacrosUpdateResponseComposite =
  tenantsUidMacrosUpdateResponse204;

export type tenantsUidMacrosUpdateResponse =
  tenantsUidMacrosUpdateResponseComposite & {
    headers: Headers;
  };

export const getTenantsUidMacrosUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/macros`;
};

export const tenantsUidMacrosUpdate = async (
  tenantUid: string,
  v1MacrosBody: V1MacrosBody,
  options?: RequestInit,
): Promise<tenantsUidMacrosUpdateResponse> => {
  return customInstance<tenantsUidMacrosUpdateResponse>(
    getTenantsUidMacrosUpdateUrl(tenantUid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1MacrosBody),
    },
  );
};

/**
 * @summary Returns the oidc Spec for tenant
 */
export type v1TenantUidOidcConfigGetResponse200 = {
  data: TenantOidcClientSpec;
  status: 200;
};

export type v1TenantUidOidcConfigGetResponseComposite =
  v1TenantUidOidcConfigGetResponse200;

export type v1TenantUidOidcConfigGetResponse =
  v1TenantUidOidcConfigGetResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidOidcConfigGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/oidc/config`;
};

export const v1TenantUidOidcConfigGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<v1TenantUidOidcConfigGetResponse> => {
  return customInstance<v1TenantUidOidcConfigGetResponse>(
    getV1TenantUidOidcConfigGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Associates the  oidc Spec for the tenant
 */
export type v1TenantUidOidcConfigUpdateResponse204 = {
  data: void;
  status: 204;
};

export type v1TenantUidOidcConfigUpdateResponseComposite =
  v1TenantUidOidcConfigUpdateResponse204;

export type v1TenantUidOidcConfigUpdateResponse =
  v1TenantUidOidcConfigUpdateResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidOidcConfigUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/oidc/config`;
};

export const v1TenantUidOidcConfigUpdate = async (
  tenantUid: string,
  tenantOidcClientSpec: TenantOidcClientSpec,
  options?: RequestInit,
): Promise<v1TenantUidOidcConfigUpdateResponse> => {
  return customInstance<v1TenantUidOidcConfigUpdateResponse>(
    getV1TenantUidOidcConfigUpdateUrl(tenantUid),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(tenantOidcClientSpec),
    },
  );
};

/**
 * @summary retrieves the password policy for tenant
 */
export type v1TenantUidPasswordPolicyGetResponse200 = {
  data: TenantPasswordPolicyEntity;
  status: 200;
};

export type v1TenantUidPasswordPolicyGetResponseComposite =
  v1TenantUidPasswordPolicyGetResponse200;

export type v1TenantUidPasswordPolicyGetResponse =
  v1TenantUidPasswordPolicyGetResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidPasswordPolicyGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/password/policy`;
};

export const v1TenantUidPasswordPolicyGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<v1TenantUidPasswordPolicyGetResponse> => {
  return customInstance<v1TenantUidPasswordPolicyGetResponse>(
    getV1TenantUidPasswordPolicyGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary creates or updates a password policy for tenant
 */
export type v1TenantUidPasswordPolicyUpdateResponse204 = {
  data: void;
  status: 204;
};

export type v1TenantUidPasswordPolicyUpdateResponseComposite =
  v1TenantUidPasswordPolicyUpdateResponse204;

export type v1TenantUidPasswordPolicyUpdateResponse =
  v1TenantUidPasswordPolicyUpdateResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidPasswordPolicyUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/password/policy`;
};

export const v1TenantUidPasswordPolicyUpdate = async (
  tenantUid: string,
  tenantPasswordPolicyEntity: TenantPasswordPolicyEntity,
  options?: RequestInit,
): Promise<v1TenantUidPasswordPolicyUpdateResponse> => {
  return customInstance<v1TenantUidPasswordPolicyUpdateResponse>(
    getV1TenantUidPasswordPolicyUpdateUrl(tenantUid),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(tenantPasswordPolicyEntity),
    },
  );
};

/**
 * @summary Get is cluster group enabled for a specific tenant
 */
export type v1TenantPrefClusterGroupGetResponse200 = {
  data: TenantEnableClusterGroup;
  status: 200;
};

export type v1TenantPrefClusterGroupGetResponseComposite =
  v1TenantPrefClusterGroupGetResponse200;

export type v1TenantPrefClusterGroupGetResponse =
  v1TenantPrefClusterGroupGetResponseComposite & {
    headers: Headers;
  };

export const getV1TenantPrefClusterGroupGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/preferences/clusterGroup`;
};

export const v1TenantPrefClusterGroupGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<v1TenantPrefClusterGroupGetResponse> => {
  return customInstance<v1TenantPrefClusterGroupGetResponse>(
    getV1TenantPrefClusterGroupGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Enable or Disable cluster group for a specific tenant
 */
export type v1TenantPrefClusterGroupUpdateResponse204 = {
  data: void;
  status: 204;
};

export type v1TenantPrefClusterGroupUpdateResponseComposite =
  v1TenantPrefClusterGroupUpdateResponse204;

export type v1TenantPrefClusterGroupUpdateResponse =
  v1TenantPrefClusterGroupUpdateResponseComposite & {
    headers: Headers;
  };

export const getV1TenantPrefClusterGroupUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/preferences/clusterGroup`;
};

export const v1TenantPrefClusterGroupUpdate = async (
  tenantUid: string,
  tenantEnableClusterGroup: TenantEnableClusterGroup,
  options?: RequestInit,
): Promise<v1TenantPrefClusterGroupUpdateResponse> => {
  return customInstance<v1TenantPrefClusterGroupUpdateResponse>(
    getV1TenantPrefClusterGroupUpdateUrl(tenantUid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(tenantEnableClusterGroup),
    },
  );
};

/**
 * @summary Get tenant cluster settings
 */
export type tenantClusterSettingsGetResponse200 = {
  data: TenantClusterSettings;
  status: 200;
};

export type tenantClusterSettingsGetResponseComposite =
  tenantClusterSettingsGetResponse200;

export type tenantClusterSettingsGetResponse =
  tenantClusterSettingsGetResponseComposite & {
    headers: Headers;
  };

export const getTenantClusterSettingsGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/preferences/clusterSettings`;
};

export const tenantClusterSettingsGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<tenantClusterSettingsGetResponse> => {
  return customInstance<tenantClusterSettingsGetResponse>(
    getTenantClusterSettingsGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update tenant clusters nodes auto remediation setting
 */
export type tenantClustersNodesAutoRemediationSettingUpdateResponse204 = {
  data: void;
  status: 204;
};

export type tenantClustersNodesAutoRemediationSettingUpdateResponseComposite =
  tenantClustersNodesAutoRemediationSettingUpdateResponse204;

export type tenantClustersNodesAutoRemediationSettingUpdateResponse =
  tenantClustersNodesAutoRemediationSettingUpdateResponseComposite & {
    headers: Headers;
  };

export const getTenantClustersNodesAutoRemediationSettingUpdateUrl = (
  tenantUid: string,
) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/preferences/clusterSettings/nodesAutoRemediationSetting`;
};

export const tenantClustersNodesAutoRemediationSettingUpdate = async (
  tenantUid: string,
  v1NodesAutoRemediationSettingsBody: V1NodesAutoRemediationSettingsBody,
  options?: RequestInit,
): Promise<tenantClustersNodesAutoRemediationSettingUpdateResponse> => {
  return customInstance<tenantClustersNodesAutoRemediationSettingUpdateResponse>(
    getTenantClustersNodesAutoRemediationSettingUpdateUrl(tenantUid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1NodesAutoRemediationSettingsBody),
    },
  );
};

/**
 * @summary Get developer credit enabled for a specific tenant
 */
export type v1TenantDeveloperCreditGetResponse200 = {
  data: DeveloperCredit;
  status: 200;
};

export type v1TenantDeveloperCreditGetResponseComposite =
  v1TenantDeveloperCreditGetResponse200;

export type v1TenantDeveloperCreditGetResponse =
  v1TenantDeveloperCreditGetResponseComposite & {
    headers: Headers;
  };

export const getV1TenantDeveloperCreditGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/preferences/developerCredit`;
};

export const v1TenantDeveloperCreditGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<v1TenantDeveloperCreditGetResponse> => {
  return customInstance<v1TenantDeveloperCreditGetResponse>(
    getV1TenantDeveloperCreditGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary update developer credit for a specific tenant
 */
export type v1TenantDeveloperCreditUpdateResponse204 = {
  data: void;
  status: 204;
};

export type v1TenantDeveloperCreditUpdateResponseComposite =
  v1TenantDeveloperCreditUpdateResponse204;

export type v1TenantDeveloperCreditUpdateResponse =
  v1TenantDeveloperCreditUpdateResponseComposite & {
    headers: Headers;
  };

export const getV1TenantDeveloperCreditUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/preferences/developerCredit`;
};

export const v1TenantDeveloperCreditUpdate = async (
  tenantUid: string,
  developerCredit: DeveloperCredit,
  options?: RequestInit,
): Promise<v1TenantDeveloperCreditUpdateResponse> => {
  return customInstance<v1TenantDeveloperCreditUpdateResponse>(
    getV1TenantDeveloperCreditUpdateUrl(tenantUid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(developerCredit),
    },
  );
};

/**
 * @summary Get tenant fips settings
 */
export type tenantFipsSettingsGetResponse200 = {
  data: FipsSettings;
  status: 200;
};

export type tenantFipsSettingsGetResponseComposite =
  tenantFipsSettingsGetResponse200;

export type tenantFipsSettingsGetResponse =
  tenantFipsSettingsGetResponseComposite & {
    headers: Headers;
  };

export const getTenantFipsSettingsGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/preferences/fips`;
};

export const tenantFipsSettingsGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<tenantFipsSettingsGetResponse> => {
  return customInstance<tenantFipsSettingsGetResponse>(
    getTenantFipsSettingsGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update tenant fips setting
 */
export type tenantFipsSettingsUpdateResponse204 = {
  data: void;
  status: 204;
};

export type tenantFipsSettingsUpdateResponseComposite =
  tenantFipsSettingsUpdateResponse204;

export type tenantFipsSettingsUpdateResponse =
  tenantFipsSettingsUpdateResponseComposite & {
    headers: Headers;
  };

export const getTenantFipsSettingsUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/preferences/fips`;
};

export const tenantFipsSettingsUpdate = async (
  tenantUid: string,
  fipsSettings: FipsSettings,
  options?: RequestInit,
): Promise<tenantFipsSettingsUpdateResponse> => {
  return customInstance<tenantFipsSettingsUpdateResponse>(
    getTenantFipsSettingsUpdateUrl(tenantUid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(fipsSettings),
    },
  );
};

/**
 * @summary Get all rate config for public and private cloud
 */
export type rateConfigGetResponse200 = {
  data: RateConfig;
  status: 200;
};

export type rateConfigGetResponseComposite = rateConfigGetResponse200;

export type rateConfigGetResponse = rateConfigGetResponseComposite & {
  headers: Headers;
};

export const getRateConfigGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/rateConfig`;
};

export const rateConfigGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<rateConfigGetResponse> => {
  return customInstance<rateConfigGetResponse>(getRateConfigGetUrl(tenantUid), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary updates the rate config for public and private cloud
 */
export type rateConfigUpdateResponse204 = {
  data: void;
  status: 204;
};

export type rateConfigUpdateResponseComposite = rateConfigUpdateResponse204;

export type rateConfigUpdateResponse = rateConfigUpdateResponseComposite & {
  headers: Headers;
};

export const getRateConfigUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/rateConfig`;
};

export const rateConfigUpdate = async (
  tenantUid: string,
  rateConfig: RateConfig,
  options?: RequestInit,
): Promise<rateConfigUpdateResponse> => {
  return customInstance<rateConfigUpdateResponse>(
    getRateConfigUpdateUrl(tenantUid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(rateConfig),
    },
  );
};

/**
 * @summary Get tenant level resource limits configuration
 */
export type tenantResourceLimitsGetResponse200 = {
  data: TenantResourceLimits;
  status: 200;
};

export type tenantResourceLimitsGetResponseComposite =
  tenantResourceLimitsGetResponse200;

export type tenantResourceLimitsGetResponse =
  tenantResourceLimitsGetResponseComposite & {
    headers: Headers;
  };

export const getTenantResourceLimitsGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/resourceLimits`;
};

export const tenantResourceLimitsGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<tenantResourceLimitsGetResponse> => {
  return customInstance<tenantResourceLimitsGetResponse>(
    getTenantResourceLimitsGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update tenant resource limits configuration
 */
export type tenantResourceLimitsUpdateResponse204 = {
  data: void;
  status: 204;
};

export type tenantResourceLimitsUpdateResponseComposite =
  tenantResourceLimitsUpdateResponse204;

export type tenantResourceLimitsUpdateResponse =
  tenantResourceLimitsUpdateResponseComposite & {
    headers: Headers;
  };

export const getTenantResourceLimitsUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/resourceLimits`;
};

export const tenantResourceLimitsUpdate = async (
  tenantUid: string,
  tenantResourceLimitsEntity: TenantResourceLimitsEntity,
  options?: RequestInit,
): Promise<tenantResourceLimitsUpdateResponse> => {
  return customInstance<tenantResourceLimitsUpdateResponse>(
    getTenantResourceLimitsUpdateUrl(tenantUid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(tenantResourceLimitsEntity),
    },
  );
};

/**
 * @summary Returns the specified service provider metadata and Saml Spec for tenant
 */
export type v1TenantUidSamlConfigSpecGetResponse200 = {
  data: TenantSamlSpec;
  status: 200;
};

export type v1TenantUidSamlConfigSpecGetResponseComposite =
  v1TenantUidSamlConfigSpecGetResponse200;

export type v1TenantUidSamlConfigSpecGetResponse =
  v1TenantUidSamlConfigSpecGetResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidSamlConfigSpecGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/saml/config`;
};

export const v1TenantUidSamlConfigSpecGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<v1TenantUidSamlConfigSpecGetResponse> => {
  return customInstance<v1TenantUidSamlConfigSpecGetResponse>(
    getV1TenantUidSamlConfigSpecGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Associates the specified federation metadata for the tenant
 */
export type v1TenantUidSamlConfigUpdateResponse204 = {
  data: void;
  status: 204;
};

export type v1TenantUidSamlConfigUpdateResponseComposite =
  v1TenantUidSamlConfigUpdateResponse204;

export type v1TenantUidSamlConfigUpdateResponse =
  v1TenantUidSamlConfigUpdateResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidSamlConfigUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/saml/config`;
};

export const v1TenantUidSamlConfigUpdate = async (
  tenantUid: string,
  tenantSamlRequestSpec: TenantSamlRequestSpec,
  options?: RequestInit,
): Promise<v1TenantUidSamlConfigUpdateResponse> => {
  return customInstance<v1TenantUidSamlConfigUpdateResponse>(
    getV1TenantUidSamlConfigUpdateUrl(tenantUid),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(tenantSamlRequestSpec),
    },
  );
};

/**
 * @summary get sso logins for the tenants
 */
export type v1TenantUidSsoAuthProvidersGetResponse200 = {
  data: TenantSsoAuthProvidersEntity;
  status: 200;
};

export type v1TenantUidSsoAuthProvidersGetResponseComposite =
  v1TenantUidSsoAuthProvidersGetResponse200;

export type v1TenantUidSsoAuthProvidersGetResponse =
  v1TenantUidSsoAuthProvidersGetResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidSsoAuthProvidersGetUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/sso/auth/providers`;
};

export const v1TenantUidSsoAuthProvidersGet = async (
  tenantUid: string,
  options?: RequestInit,
): Promise<v1TenantUidSsoAuthProvidersGetResponse> => {
  return customInstance<v1TenantUidSsoAuthProvidersGetResponse>(
    getV1TenantUidSsoAuthProvidersGetUrl(tenantUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary enable sso logins for the tenants
 */
export type v1TenantUidSsoAuthProvidersUpdateResponse204 = {
  data: void;
  status: 204;
};

export type v1TenantUidSsoAuthProvidersUpdateResponseComposite =
  v1TenantUidSsoAuthProvidersUpdateResponse204;

export type v1TenantUidSsoAuthProvidersUpdateResponse =
  v1TenantUidSsoAuthProvidersUpdateResponseComposite & {
    headers: Headers;
  };

export const getV1TenantUidSsoAuthProvidersUpdateUrl = (tenantUid: string) => {
  return `https://api.spectrocloud.com/v1/tenants/${tenantUid}/sso/auth/providers`;
};

export const v1TenantUidSsoAuthProvidersUpdate = async (
  tenantUid: string,
  tenantSsoAuthProvidersEntity: TenantSsoAuthProvidersEntity,
  options?: RequestInit,
): Promise<v1TenantUidSsoAuthProvidersUpdateResponse> => {
  return customInstance<v1TenantUidSsoAuthProvidersUpdateResponse>(
    getV1TenantUidSsoAuthProvidersUpdateUrl(tenantUid),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(tenantSsoAuthProvidersEntity),
    },
  );
};
