/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */

/**
 * Tenant Address
 */
export interface Address {
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  country?: string;
  pincode?: string;
  state?: string;
}
