/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */

/**
 * Application deployment profile metadata
 */
export interface AppDeploymentProfileMeta {
  /** Application deployment profile name */
  name?: string;
  /** Application deployment profile uid */
  uid?: string;
  /** Application deployment profile version */
  version?: string;
}
