/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */

/**
 * Auth certs get
 */
export interface AuthCertsGet {
  apiDomain?: string;
  caCert?: string;
  insecureSkipVerify?: boolean;
  rootDomain?: string;
}
