/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type { UrlEncodedBase64 } from "./urlEncodedBase64";

export type AuthMfaLoginFinishRequestResponse = {
  authenticatorData?: UrlEncodedBase64;
  clientDataJSON?: UrlEncodedBase64;
  signature?: UrlEncodedBase64;
  userHandle?: UrlEncodedBase64;
};
