/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */

/**
 * Azure Machine Spec Image
 */
export interface AzureMachineSpecImage {
  gallery?: string;
  id?: string;
  name?: string;
  offer?: string;
  publisher?: string;
  resourceGroup?: string;
  sku?: string;
  subscriptionId?: string;
  version?: string;
}
