/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type { Time } from "./time";
import type { ClusterState } from "./clusterState";

/**
 * Active cluster meta
 */
export interface ClusterMeta {
  cloudType?: string;
  clusterType?: string;
  creationTimestamp?: Time;
  duration?: string;
  name?: string;
  projectName?: string;
  state?: ClusterState;
  uid?: string;
}
