/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type { ClusterMeta } from "./clusterMeta";

/**
 * Active clusters information
 */
export interface ClustersInfo {
  clustersMeta?: ClusterMeta[];
  totalActiveClusters?: number;
  totalActiveGreenFieldClusters?: number;
  totalActiveImportedClusters?: number;
  totalClustersDeleted?: number;
  totalClustersDeployed?: number;
}
