/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */

/**
 * Cluster namespace resource allocation
 */
export interface ClusterNamespaceResourceAllocation {
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  cpuCores?: number;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  memoryMiB?: number;
}
