/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type { EdgeHostHealthState } from "./edgeHostHealthState";

/**
 * EdgeHostHealth defines the desired health state of EdgeHostDevice
 */
export interface EdgeHostHealth {
  agentVersion?: string;
  message?: string;
  state?: EdgeHostHealthState;
}
