/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */

/**
 * A zone is a deployment area for Google Cloud resources within a region
 */
export interface GcpZone {
  /** GCP zone name */
  name?: string;
}
