/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */

export interface GrpcClientMonitoringData {
  clientUid?: string;
  receivedBroadcastCount?: number;
  receivedPublishedCount?: number;
  sentBroadcastCount?: number;
  sentPublishedCount?: number;
  subjects?: string[];
}
