/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */

/**
 * Maas vlan entity
 */
export interface MaasVlan {
  /** Fabric associated with Maas Vlan */
  fabric?: string;
  /** Id of Maas Vlan */
  id?: number;
  /** Name of Maas Vlan */
  name?: string;
}
