/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type { URLEncodedBase64 } from "./urlEncodedBase64";

export interface MfaCredentialDescriptor {
  attestationType?: string;
  id?: URLEncodedBase64;
  transports?: string[];
  type?: string;
}
