/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type { MfaCredentialDescriptor } from "./mfaCredentialDescriptor";
import type { URLEncodedBase64 } from "./urlEncodedBase64";
import type { MfaAuthenticationExtensions } from "./mfaAuthenticationExtensions";

export interface MfaPublicKeyCredentialRequestOptions {
  allowCredentials?: MfaCredentialDescriptor[];
  challenge?: URLEncodedBase64;
  extensions?: MfaAuthenticationExtensions;
  rpId?: string;
  timeout?: number;
  userVerification?: string;
}
