/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type { SpectroClusterHealthStatus } from "./spectroClusterHealthStatus";
import type { ClusterNotificationStatus } from "./clusterNotificationStatus";

/**
 * Overload status
 */
export interface OverloadStatus {
  health?: SpectroClusterHealthStatus;
  isActive?: boolean;
  isReady?: boolean;
  kubectlCommands?: string[];
  notifications?: ClusterNotificationStatus;
  state?: string;
}
