/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type { ResourceReference } from "./resourceReference";
import type { ResourceUsageDataPoint } from "./resourceUsageDataPoint";

/**
 * Resource usage summary information
 */
export interface ResourceUsageSummary {
  associatedResources?: ResourceReference[];
  data?: ResourceUsageDataPoint[];
  entity?: ResourceReference;
}
