/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type { ResourceConsumption } from "./resourceConsumption";
import type { ResourceTotalConsumptionData } from "./resourceTotalConsumptionData";

/**
 * Resources consumption information
 */
export interface ResourcesConsumption {
  cpuUnit?: string;
  memoryUnit?: string;
  resources?: ResourceConsumption[];
  total?: ResourceTotalConsumptionData;
}
