/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type { SearchFilterKeyValueConditionMatch } from "./searchFilterKeyValueConditionMatch";
import type { SearchFilterStringOperator } from "./searchFilterStringOperator";

export interface SearchFilterKeyValueCondition {
  ignoreCase?: boolean;
  key?: string;
  match?: SearchFilterKeyValueConditionMatch;
  negation?: boolean;
  operator?: SearchFilterStringOperator;
}
