/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type { Time } from "./time";

/**
 * Returns spectro cluster pair meta
 */
export interface SpectroClusterPairingRequestMeta {
  /** Cluster cloud type */
  cloudType?: string;
  /** Spectro cluster uid */
  clusterUid?: string;
  creationTimestamp?: Time;
  /** Cluster uid in the local UI */
  localClusterUid?: string;
  /** Spectro cluster name */
  name?: string;
  /** Cluster pairing uid */
  pairingUid?: string;
  /** State of the spectro cluster pairing request */
  state?: string;
}
