/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */

/**
 * system backup s3 storage config spec
 */
export interface SystemS3Spec {
  accessKey?: string;
  bucket?: string;
  folder?: string;
  region?: string;
  secretKey?: string;
}
