/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type { Time } from "./time";

/**
 * Tenant Password Policy Entity
 */
export interface TenantPasswordPolicyEntity {
  creationTimestamp?: Time;
  expiryDurationInDays?: number;
  firstReminderInDays?: number;
  isRegex?: boolean;
  minLength?: number;
  minNumOfBlockLetters?: number;
  minNumOfDigits?: number;
  minNumOfSmallLetters?: number;
  minNumOfSpecialCharacters?: number;
  regex?: string;
  updateTimestamp?: Time;
}
