/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */

/**
 * Chassis specifies the chassis info passed to the domain.
 */
export interface VmChassis {
  asset?: string;
  manufacturer?: string;
  serial?: string;
  sku?: string;
  version?: string;
}
