/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type {
  EdgeHostClusterEntity,
  EdgeHostConfig,
  EdgeHostDevice,
  EdgeHostDeviceEntity,
  EdgeHostDeviceHostCheckSum,
  EdgeHostDeviceHostPairingKey,
  EdgeHostDeviceMetaUpdateEntity,
  EdgeHostDevicesUidGetParams,
  EdgeHostDevicesUidPackManifestsUidGetParams,
  EdgeHostDevicesUidProfilesGetParams,
  EdgeHostHealth,
  EdgeHostVsphereCloudProperties,
  EdgeHostsMeta,
  EdgeHostsMetadataQuickFilterGetParams,
  EdgeHostsTags,
  EdgeToken,
  EdgeTokenActiveState,
  EdgeTokenEntity,
  EdgeTokenUpdate,
  EdgeTokens,
  Manifest,
  SpectroClusterProfileList,
  SpectroTunnelConfig,
  SpectroTunnelStatus,
  Uid,
  V1EdgeHostDeviceBody,
  V1SpectroClusterPacksStatusEntityBody,
  V1SpectroClusterProfilesBody,
} from ".././schemas";

import { customInstance } from ".././httpClient/customClient";

/**
 * @summary Create the edge host device
 */
export type edgeHostDevicesCreateResponse201 = {
  data: Uid;
  status: 201;
};

export type edgeHostDevicesCreateResponseComposite =
  edgeHostDevicesCreateResponse201;

export type edgeHostDevicesCreateResponse =
  edgeHostDevicesCreateResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesCreateUrl = () => {
  return `https://api.spectrocloud.com/v1/edgehosts`;
};

export const edgeHostDevicesCreate = async (
  edgeHostDeviceEntity: EdgeHostDeviceEntity,
  options?: RequestInit,
): Promise<edgeHostDevicesCreateResponse> => {
  return customInstance<edgeHostDevicesCreateResponse>(
    getEdgeHostDevicesCreateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(edgeHostDeviceEntity),
    },
  );
};

/**
 * @summary Retrieves a list of edge hosts metadata matching the filter condition
 */
export type edgeHostsMetadataQuickFilterGetResponse200 = {
  data: EdgeHostsMeta;
  status: 200;
};

export type edgeHostsMetadataQuickFilterGetResponseComposite =
  edgeHostsMetadataQuickFilterGetResponse200;

export type edgeHostsMetadataQuickFilterGetResponse =
  edgeHostsMetadataQuickFilterGetResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostsMetadataQuickFilterGetUrl = (
  params?: EdgeHostsMetadataQuickFilterGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.spectrocloud.com/v1/edgehosts/metadata?${stringifiedParams}`
    : `https://api.spectrocloud.com/v1/edgehosts/metadata`;
};

export const edgeHostsMetadataQuickFilterGet = async (
  params?: EdgeHostsMetadataQuickFilterGetParams,
  options?: RequestInit,
): Promise<edgeHostsMetadataQuickFilterGetResponse> => {
  return customInstance<edgeHostsMetadataQuickFilterGetResponse>(
    getEdgeHostsMetadataQuickFilterGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Registers the edge host device
 */
export type edgeHostDevicesRegisterResponse200 = {
  data: EdgeHostDevice;
  status: 200;
};

export type edgeHostDevicesRegisterResponseComposite =
  edgeHostDevicesRegisterResponse200;

export type edgeHostDevicesRegisterResponse =
  edgeHostDevicesRegisterResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesRegisterUrl = () => {
  return `https://api.spectrocloud.com/v1/edgehosts/register`;
};

export const edgeHostDevicesRegister = async (
  v1EdgeHostDeviceBody: V1EdgeHostDeviceBody,
  options?: RequestInit,
): Promise<edgeHostDevicesRegisterResponse> => {
  return customInstance<edgeHostDevicesRegisterResponse>(
    getEdgeHostDevicesRegisterUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1EdgeHostDeviceBody),
    },
  );
};

/**
 * @summary Retrieves a list of edge hosts tags
 */
export type edgeHostsTagsGetResponse200 = {
  data: EdgeHostsTags;
  status: 200;
};

export type edgeHostsTagsGetResponseComposite = edgeHostsTagsGetResponse200;

export type edgeHostsTagsGetResponse = edgeHostsTagsGetResponseComposite & {
  headers: Headers;
};

export const getEdgeHostsTagsGetUrl = () => {
  return `https://api.spectrocloud.com/v1/edgehosts/tags`;
};

export const edgeHostsTagsGet = async (
  options?: RequestInit,
): Promise<edgeHostsTagsGetResponse> => {
  return customInstance<edgeHostsTagsGetResponse>(getEdgeHostsTagsGetUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Retrieves a list of edge tokens
 */
export type edgeTokensListResponse200 = {
  data: EdgeTokens;
  status: 200;
};

export type edgeTokensListResponseComposite = edgeTokensListResponse200;

export type edgeTokensListResponse = edgeTokensListResponseComposite & {
  headers: Headers;
};

export const getEdgeTokensListUrl = () => {
  return `https://api.spectrocloud.com/v1/edgehosts/tokens`;
};

export const edgeTokensList = async (
  options?: RequestInit,
): Promise<edgeTokensListResponse> => {
  return customInstance<edgeTokensListResponse>(getEdgeTokensListUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create the edge token
 */
export type edgeTokensCreateResponse201 = {
  data: Uid;
  status: 201;
};

export type edgeTokensCreateResponseComposite = edgeTokensCreateResponse201;

export type edgeTokensCreateResponse = edgeTokensCreateResponseComposite & {
  headers: Headers;
};

export const getEdgeTokensCreateUrl = () => {
  return `https://api.spectrocloud.com/v1/edgehosts/tokens`;
};

export const edgeTokensCreate = async (
  edgeTokenEntity: EdgeTokenEntity,
  options?: RequestInit,
): Promise<edgeTokensCreateResponse> => {
  return customInstance<edgeTokensCreateResponse>(getEdgeTokensCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(edgeTokenEntity),
  });
};

/**
 * @summary Deletes the specified edge token
 */
export type edgeTokensUidDeleteResponse204 = {
  data: void;
  status: 204;
};

export type edgeTokensUidDeleteResponseComposite =
  edgeTokensUidDeleteResponse204;

export type edgeTokensUidDeleteResponse =
  edgeTokensUidDeleteResponseComposite & {
    headers: Headers;
  };

export const getEdgeTokensUidDeleteUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/tokens/${uid}`;
};

export const edgeTokensUidDelete = async (
  uid: string,
  options?: RequestInit,
): Promise<edgeTokensUidDeleteResponse> => {
  return customInstance<edgeTokensUidDeleteResponse>(
    getEdgeTokensUidDeleteUrl(uid),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Returns the specified edge token
 */
export type edgeTokensUidGetResponse200 = {
  data: EdgeToken;
  status: 200;
};

export type edgeTokensUidGetResponseComposite = edgeTokensUidGetResponse200;

export type edgeTokensUidGetResponse = edgeTokensUidGetResponseComposite & {
  headers: Headers;
};

export const getEdgeTokensUidGetUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/tokens/${uid}`;
};

export const edgeTokensUidGet = async (
  uid: string,
  options?: RequestInit,
): Promise<edgeTokensUidGetResponse> => {
  return customInstance<edgeTokensUidGetResponse>(getEdgeTokensUidGetUrl(uid), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Updates the specified edge token
 */
export type edgeTokensUidUpdateResponse204 = {
  data: void;
  status: 204;
};

export type edgeTokensUidUpdateResponseComposite =
  edgeTokensUidUpdateResponse204;

export type edgeTokensUidUpdateResponse =
  edgeTokensUidUpdateResponseComposite & {
    headers: Headers;
  };

export const getEdgeTokensUidUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/tokens/${uid}`;
};

export const edgeTokensUidUpdate = async (
  uid: string,
  edgeTokenUpdate: EdgeTokenUpdate,
  options?: RequestInit,
): Promise<edgeTokensUidUpdateResponse> => {
  return customInstance<edgeTokensUidUpdateResponse>(
    getEdgeTokensUidUpdateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(edgeTokenUpdate),
    },
  );
};

/**
 * @summary Revoke or re-activate the edge token access
 */
export type edgeTokensUidStateResponse204 = {
  data: void;
  status: 204;
};

export type edgeTokensUidStateResponseComposite = edgeTokensUidStateResponse204;

export type edgeTokensUidStateResponse = edgeTokensUidStateResponseComposite & {
  headers: Headers;
};

export const getEdgeTokensUidStateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/tokens/${uid}/state`;
};

export const edgeTokensUidState = async (
  uid: string,
  edgeTokenActiveState: EdgeTokenActiveState,
  options?: RequestInit,
): Promise<edgeTokensUidStateResponse> => {
  return customInstance<edgeTokensUidStateResponse>(
    getEdgeTokensUidStateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(edgeTokenActiveState),
    },
  );
};

/**
 * @summary Deletes the specified edge host device
 */
export type edgeHostDevicesUidDeleteResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDevicesUidDeleteResponseComposite =
  edgeHostDevicesUidDeleteResponse204;

export type edgeHostDevicesUidDeleteResponse =
  edgeHostDevicesUidDeleteResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidDeleteUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}`;
};

export const edgeHostDevicesUidDelete = async (
  uid: string,
  options?: RequestInit,
): Promise<edgeHostDevicesUidDeleteResponse> => {
  return customInstance<edgeHostDevicesUidDeleteResponse>(
    getEdgeHostDevicesUidDeleteUrl(uid),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Returns the specified edge host device
 */
export type edgeHostDevicesUidGetResponse200 = {
  data: EdgeHostDevice;
  status: 200;
};

export type edgeHostDevicesUidGetResponseComposite =
  edgeHostDevicesUidGetResponse200;

export type edgeHostDevicesUidGetResponse =
  edgeHostDevicesUidGetResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidGetUrl = (
  uid: string,
  params?: EdgeHostDevicesUidGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.spectrocloud.com/v1/edgehosts/${uid}?${stringifiedParams}`
    : `https://api.spectrocloud.com/v1/edgehosts/${uid}`;
};

export const edgeHostDevicesUidGet = async (
  uid: string,
  params?: EdgeHostDevicesUidGetParams,
  options?: RequestInit,
): Promise<edgeHostDevicesUidGetResponse> => {
  return customInstance<edgeHostDevicesUidGetResponse>(
    getEdgeHostDevicesUidGetUrl(uid, params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Updates the specified edge host device
 */
export type edgeHostDevicesUidUpdateResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDevicesUidUpdateResponseComposite =
  edgeHostDevicesUidUpdateResponse204;

export type edgeHostDevicesUidUpdateResponse =
  edgeHostDevicesUidUpdateResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}`;
};

export const edgeHostDevicesUidUpdate = async (
  uid: string,
  v1EdgeHostDeviceBody: V1EdgeHostDeviceBody,
  options?: RequestInit,
): Promise<edgeHostDevicesUidUpdateResponse> => {
  return customInstance<edgeHostDevicesUidUpdateResponse>(
    getEdgeHostDevicesUidUpdateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1EdgeHostDeviceBody),
    },
  );
};

/**
 * @summary Deassociate the clusters to the edge host
 */
export type edgeHostDevicesUidClusterDeassociateResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDevicesUidClusterDeassociateResponseComposite =
  edgeHostDevicesUidClusterDeassociateResponse204;

export type edgeHostDevicesUidClusterDeassociateResponse =
  edgeHostDevicesUidClusterDeassociateResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidClusterDeassociateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/cluster/associate`;
};

export const edgeHostDevicesUidClusterDeassociate = async (
  uid: string,
  options?: RequestInit,
): Promise<edgeHostDevicesUidClusterDeassociateResponse> => {
  return customInstance<edgeHostDevicesUidClusterDeassociateResponse>(
    getEdgeHostDevicesUidClusterDeassociateUrl(uid),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Associate the clusters to the edge host
 */
export type edgeHostDevicesUidClusterAssociateResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDevicesUidClusterAssociateResponseComposite =
  edgeHostDevicesUidClusterAssociateResponse204;

export type edgeHostDevicesUidClusterAssociateResponse =
  edgeHostDevicesUidClusterAssociateResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidClusterAssociateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/cluster/associate`;
};

export const edgeHostDevicesUidClusterAssociate = async (
  uid: string,
  edgeHostClusterEntity: EdgeHostClusterEntity,
  options?: RequestInit,
): Promise<edgeHostDevicesUidClusterAssociateResponse> => {
  return customInstance<edgeHostDevicesUidClusterAssociateResponse>(
    getEdgeHostDevicesUidClusterAssociateUrl(uid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(edgeHostClusterEntity),
    },
  );
};

/**
 * @summary Get the specified edge host device configuration
 */
export type edgeHostDevicesUidConfigGetResponse200 = {
  data: EdgeHostConfig;
  status: 200;
};

export type edgeHostDevicesUidConfigGetResponseComposite =
  edgeHostDevicesUidConfigGetResponse200;

export type edgeHostDevicesUidConfigGetResponse =
  edgeHostDevicesUidConfigGetResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidConfigGetUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/config`;
};

export const edgeHostDevicesUidConfigGet = async (
  uid: string,
  options?: RequestInit,
): Promise<edgeHostDevicesUidConfigGetResponse> => {
  return customInstance<edgeHostDevicesUidConfigGetResponse>(
    getEdgeHostDevicesUidConfigGetUrl(uid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Updates the edge host health
 */
export type edgeHostDevicesHealthUpdateResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDevicesHealthUpdateResponseComposite =
  edgeHostDevicesHealthUpdateResponse204;

export type edgeHostDevicesHealthUpdateResponse =
  edgeHostDevicesHealthUpdateResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesHealthUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/health`;
};

export const edgeHostDevicesHealthUpdate = async (
  uid: string,
  edgeHostHealth: EdgeHostHealth,
  options?: RequestInit,
): Promise<edgeHostDevicesHealthUpdateResponse> => {
  return customInstance<edgeHostDevicesHealthUpdateResponse>(
    getEdgeHostDevicesHealthUpdateUrl(uid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(edgeHostHealth),
    },
  );
};

/**
 * @summary Update the specified edge host device host check sum
 */
export type edgeHostDeviceHostCheckSumUpdateResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDeviceHostCheckSumUpdateResponseComposite =
  edgeHostDeviceHostCheckSumUpdateResponse204;

export type edgeHostDeviceHostCheckSumUpdateResponse =
  edgeHostDeviceHostCheckSumUpdateResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDeviceHostCheckSumUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/hostCheckSum`;
};

export const edgeHostDeviceHostCheckSumUpdate = async (
  uid: string,
  edgeHostDeviceHostCheckSum: EdgeHostDeviceHostCheckSum,
  options?: RequestInit,
): Promise<edgeHostDeviceHostCheckSumUpdateResponse> => {
  return customInstance<edgeHostDeviceHostCheckSumUpdateResponse>(
    getEdgeHostDeviceHostCheckSumUpdateUrl(uid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(edgeHostDeviceHostCheckSum),
    },
  );
};

/**
 * @summary Update the specified edge host device host pairing key
 */
export type edgeHostDeviceHostPairingKeyUpdateResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDeviceHostPairingKeyUpdateResponseComposite =
  edgeHostDeviceHostPairingKeyUpdateResponse204;

export type edgeHostDeviceHostPairingKeyUpdateResponse =
  edgeHostDeviceHostPairingKeyUpdateResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDeviceHostPairingKeyUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/hostPairingKey`;
};

export const edgeHostDeviceHostPairingKeyUpdate = async (
  uid: string,
  edgeHostDeviceHostPairingKey: EdgeHostDeviceHostPairingKey,
  options?: RequestInit,
): Promise<edgeHostDeviceHostPairingKeyUpdateResponse> => {
  return customInstance<edgeHostDeviceHostPairingKeyUpdateResponse>(
    getEdgeHostDeviceHostPairingKeyUpdateUrl(uid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(edgeHostDeviceHostPairingKey),
    },
  );
};

/**
 * @summary Updates the specified edge host device meta
 */
export type edgeHostDevicesUidMetaUpdateResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDevicesUidMetaUpdateResponseComposite =
  edgeHostDevicesUidMetaUpdateResponse204;

export type edgeHostDevicesUidMetaUpdateResponse =
  edgeHostDevicesUidMetaUpdateResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidMetaUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/meta`;
};

export const edgeHostDevicesUidMetaUpdate = async (
  uid: string,
  edgeHostDeviceMetaUpdateEntity: EdgeHostDeviceMetaUpdateEntity,
  options?: RequestInit,
): Promise<edgeHostDevicesUidMetaUpdateResponse> => {
  return customInstance<edgeHostDevicesUidMetaUpdateResponse>(
    getEdgeHostDevicesUidMetaUpdateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(edgeHostDeviceMetaUpdateEntity),
    },
  );
};

/**
 * @summary Returns the specified edge host's manifest
 */
export type edgeHostDevicesUidPackManifestsUidGetResponse200 = {
  data: Manifest;
  status: 200;
};

export type edgeHostDevicesUidPackManifestsUidGetResponseComposite =
  edgeHostDevicesUidPackManifestsUidGetResponse200;

export type edgeHostDevicesUidPackManifestsUidGetResponse =
  edgeHostDevicesUidPackManifestsUidGetResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidPackManifestsUidGetUrl = (
  uid: string,
  manifestUid: string,
  params?: EdgeHostDevicesUidPackManifestsUidGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.spectrocloud.com/v1/edgehosts/${uid}/pack/manifests/${manifestUid}?${stringifiedParams}`
    : `https://api.spectrocloud.com/v1/edgehosts/${uid}/pack/manifests/${manifestUid}`;
};

export const edgeHostDevicesUidPackManifestsUidGet = async (
  uid: string,
  manifestUid: string,
  params?: EdgeHostDevicesUidPackManifestsUidGetParams,
  options?: RequestInit,
): Promise<edgeHostDevicesUidPackManifestsUidGetResponse> => {
  return customInstance<edgeHostDevicesUidPackManifestsUidGetResponse>(
    getEdgeHostDevicesUidPackManifestsUidGetUrl(uid, manifestUid, params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Patch update specified edge host's packs status
 */
export type edgeHostDevicesUidPacksStatusPatchResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDevicesUidPacksStatusPatchResponseComposite =
  edgeHostDevicesUidPacksStatusPatchResponse204;

export type edgeHostDevicesUidPacksStatusPatchResponse =
  edgeHostDevicesUidPacksStatusPatchResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidPacksStatusPatchUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/packs/status`;
};

export const edgeHostDevicesUidPacksStatusPatch = async (
  uid: string,
  v1SpectroClusterPacksStatusEntityBody: V1SpectroClusterPacksStatusEntityBody,
  options?: RequestInit,
): Promise<edgeHostDevicesUidPacksStatusPatchResponse> => {
  return customInstance<edgeHostDevicesUidPacksStatusPatchResponse>(
    getEdgeHostDevicesUidPacksStatusPatchUrl(uid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1SpectroClusterPacksStatusEntityBody),
    },
  );
};

/**
 * @summary Returns the associated profiles of a specified edge host device
 */
export type edgeHostDevicesUidProfilesGetResponse200 = {
  data: SpectroClusterProfileList;
  status: 200;
};

export type edgeHostDevicesUidProfilesGetResponseComposite =
  edgeHostDevicesUidProfilesGetResponse200;

export type edgeHostDevicesUidProfilesGetResponse =
  edgeHostDevicesUidProfilesGetResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidProfilesGetUrl = (
  uid: string,
  params?: EdgeHostDevicesUidProfilesGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.spectrocloud.com/v1/edgehosts/${uid}/profiles?${stringifiedParams}`
    : `https://api.spectrocloud.com/v1/edgehosts/${uid}/profiles`;
};

export const edgeHostDevicesUidProfilesGet = async (
  uid: string,
  params?: EdgeHostDevicesUidProfilesGetParams,
  options?: RequestInit,
): Promise<edgeHostDevicesUidProfilesGetResponse> => {
  return customInstance<edgeHostDevicesUidProfilesGetResponse>(
    getEdgeHostDevicesUidProfilesGetUrl(uid, params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Associate cluster profiles to the specified edge host device
 */
export type edgeHostDevicesUidProfilesUpdateResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDevicesUidProfilesUpdateResponseComposite =
  edgeHostDevicesUidProfilesUpdateResponse204;

export type edgeHostDevicesUidProfilesUpdateResponse =
  edgeHostDevicesUidProfilesUpdateResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidProfilesUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/profiles`;
};

export const edgeHostDevicesUidProfilesUpdate = async (
  uid: string,
  v1SpectroClusterProfilesBody: V1SpectroClusterProfilesBody,
  options?: RequestInit,
): Promise<edgeHostDevicesUidProfilesUpdateResponse> => {
  return customInstance<edgeHostDevicesUidProfilesUpdateResponse>(
    getEdgeHostDevicesUidProfilesUpdateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1SpectroClusterProfilesBody),
    },
  );
};

/**
 * @summary Reset the cluster through edge host
 */
export type v1EdgeHostsUidResetResponse204 = {
  data: void;
  status: 204;
};

export type v1EdgeHostsUidResetResponseComposite =
  v1EdgeHostsUidResetResponse204;

export type v1EdgeHostsUidResetResponse =
  v1EdgeHostsUidResetResponseComposite & {
    headers: Headers;
  };

export const getV1EdgeHostsUidResetUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/reset`;
};

export const v1EdgeHostsUidReset = async (
  uid: string,
  options?: RequestInit,
): Promise<v1EdgeHostsUidResetResponse> => {
  return customInstance<v1EdgeHostsUidResetResponse>(
    getV1EdgeHostsUidResetUrl(uid),
    {
      ...options,
      method: "PUT",
    },
  );
};

/**
 * @summary Download the specified edge host device spc
 */
export type edgeHostDevicesUidSpcDownloadResponse200 = {
  data: Blob;
  status: 200;
};

export type edgeHostDevicesUidSpcDownloadResponseComposite =
  edgeHostDevicesUidSpcDownloadResponse200;

export type edgeHostDevicesUidSpcDownloadResponse =
  edgeHostDevicesUidSpcDownloadResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidSpcDownloadUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/spc/download`;
};

export const edgeHostDevicesUidSpcDownload = async (
  uid: string,
  options?: RequestInit,
): Promise<edgeHostDevicesUidSpcDownloadResponse> => {
  return customInstance<edgeHostDevicesUidSpcDownloadResponse>(
    getEdgeHostDevicesUidSpcDownloadUrl(uid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Updates the specified edge host device tunnel configuration
 */
export type edgeHostDevicesUidTunnelConfigUpdateResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDevicesUidTunnelConfigUpdateResponseComposite =
  edgeHostDevicesUidTunnelConfigUpdateResponse204;

export type edgeHostDevicesUidTunnelConfigUpdateResponse =
  edgeHostDevicesUidTunnelConfigUpdateResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidTunnelConfigUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/tunnelConfig`;
};

export const edgeHostDevicesUidTunnelConfigUpdate = async (
  uid: string,
  spectroTunnelConfig: SpectroTunnelConfig,
  options?: RequestInit,
): Promise<edgeHostDevicesUidTunnelConfigUpdateResponse> => {
  return customInstance<edgeHostDevicesUidTunnelConfigUpdateResponse>(
    getEdgeHostDevicesUidTunnelConfigUpdateUrl(uid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(spectroTunnelConfig),
    },
  );
};

/**
 * @summary Updates the edge host tunnel status
 */
export type edgeHostDevicesUidTunnelStatusUpdateResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDevicesUidTunnelStatusUpdateResponseComposite =
  edgeHostDevicesUidTunnelStatusUpdateResponse204;

export type edgeHostDevicesUidTunnelStatusUpdateResponse =
  edgeHostDevicesUidTunnelStatusUpdateResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidTunnelStatusUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/tunnelStatus`;
};

export const edgeHostDevicesUidTunnelStatusUpdate = async (
  uid: string,
  spectroTunnelStatus: SpectroTunnelStatus,
  options?: RequestInit,
): Promise<edgeHostDevicesUidTunnelStatusUpdateResponse> => {
  return customInstance<edgeHostDevicesUidTunnelStatusUpdateResponse>(
    getEdgeHostDevicesUidTunnelStatusUpdateUrl(uid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(spectroTunnelStatus),
    },
  );
};

/**
 * @summary Updates the specified edge host device vsphere properties
 */
export type edgeHostDevicesUidVspherePropertiesUpdateResponse204 = {
  data: void;
  status: 204;
};

export type edgeHostDevicesUidVspherePropertiesUpdateResponseComposite =
  edgeHostDevicesUidVspherePropertiesUpdateResponse204;

export type edgeHostDevicesUidVspherePropertiesUpdateResponse =
  edgeHostDevicesUidVspherePropertiesUpdateResponseComposite & {
    headers: Headers;
  };

export const getEdgeHostDevicesUidVspherePropertiesUpdateUrl = (
  uid: string,
) => {
  return `https://api.spectrocloud.com/v1/edgehosts/${uid}/vsphere/properties`;
};

export const edgeHostDevicesUidVspherePropertiesUpdate = async (
  uid: string,
  edgeHostVsphereCloudProperties: EdgeHostVsphereCloudProperties,
  options?: RequestInit,
): Promise<edgeHostDevicesUidVspherePropertiesUpdateResponse> => {
  return customInstance<edgeHostDevicesUidVspherePropertiesUpdateResponse>(
    getEdgeHostDevicesUidVspherePropertiesUpdateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(edgeHostVsphereCloudProperties),
    },
  );
};
