/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type {
  BulkEvents,
  Event,
  Events,
  EventsComponentsListParams,
  EventsComponentsObjTypeUidListParams,
  Uid,
  Uids,
} from ".././schemas";

import { customInstance } from ".././httpClient/customClient";

/**
 * Returns a paginated list of component events based on request parameters
 * @summary Returns a paginated list of component events based on request parameters
 */
export type eventsComponentsListResponse200 = {
  data: Events;
  status: 200;
};

export type eventsComponentsListResponseComposite =
  eventsComponentsListResponse200;

export type eventsComponentsListResponse =
  eventsComponentsListResponseComposite & {
    headers: Headers;
  };

export const getEventsComponentsListUrl = (
  params?: EventsComponentsListParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.spectrocloud.com/v1/events/components?${stringifiedParams}`
    : `https://api.spectrocloud.com/v1/events/components`;
};

export const eventsComponentsList = async (
  params?: EventsComponentsListParams,
  options?: RequestInit,
): Promise<eventsComponentsListResponse> => {
  return customInstance<eventsComponentsListResponse>(
    getEventsComponentsListUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Creates a component event
 * @summary Creates a component event
 */
export type eventsComponentsCreateResponse201 = {
  data: Uid;
  status: 201;
};

export type eventsComponentsCreateResponseComposite =
  eventsComponentsCreateResponse201;

export type eventsComponentsCreateResponse =
  eventsComponentsCreateResponseComposite & {
    headers: Headers;
  };

export const getEventsComponentsCreateUrl = () => {
  return `https://api.spectrocloud.com/v1/events/components`;
};

export const eventsComponentsCreate = async (
  event: Event,
  options?: RequestInit,
): Promise<eventsComponentsCreateResponse> => {
  return customInstance<eventsComponentsCreateResponse>(
    getEventsComponentsCreateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(event),
    },
  );
};

/**
 * Creates the component events in bulk
 * @summary Creates the component events in bulk
 */
export type eventsComponentsCreateBulkResponse201 = {
  data: Uids;
  status: 201;
};

export type eventsComponentsCreateBulkResponseComposite =
  eventsComponentsCreateBulkResponse201;

export type eventsComponentsCreateBulkResponse =
  eventsComponentsCreateBulkResponseComposite & {
    headers: Headers;
  };

export const getEventsComponentsCreateBulkUrl = () => {
  return `https://api.spectrocloud.com/v1/events/components/bulk`;
};

export const eventsComponentsCreateBulk = async (
  bulkEvents: BulkEvents,
  options?: RequestInit,
): Promise<eventsComponentsCreateBulkResponse> => {
  return customInstance<eventsComponentsCreateBulkResponse>(
    getEventsComponentsCreateBulkUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(bulkEvents),
    },
  );
};

/**
 * @summary Delete all the components events for the specified related object
 */
export type eventsComponentsObjTypeUidDeleteResponse204 = {
  data: void;
  status: 204;
};

export type eventsComponentsObjTypeUidDeleteResponseComposite =
  eventsComponentsObjTypeUidDeleteResponse204;

export type eventsComponentsObjTypeUidDeleteResponse =
  eventsComponentsObjTypeUidDeleteResponseComposite & {
    headers: Headers;
  };

export const getEventsComponentsObjTypeUidDeleteUrl = (
  objectKind: "spectrocluster" | "edgehost",
  objectUid: string,
) => {
  return `https://api.spectrocloud.com/v1/events/components/${objectKind}/${objectUid}`;
};

export const eventsComponentsObjTypeUidDelete = async (
  objectKind: "spectrocluster" | "edgehost",
  objectUid: string,
  options?: RequestInit,
): Promise<eventsComponentsObjTypeUidDeleteResponse> => {
  return customInstance<eventsComponentsObjTypeUidDeleteResponse>(
    getEventsComponentsObjTypeUidDeleteUrl(objectKind, objectUid),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * Returns a list of components events for the specified related object
 * @summary Returns a list of components events for the specified related object
 */
export type eventsComponentsObjTypeUidListResponse200 = {
  data: Events;
  status: 200;
};

export type eventsComponentsObjTypeUidListResponseComposite =
  eventsComponentsObjTypeUidListResponse200;

export type eventsComponentsObjTypeUidListResponse =
  eventsComponentsObjTypeUidListResponseComposite & {
    headers: Headers;
  };

export const getEventsComponentsObjTypeUidListUrl = (
  objectKind: "spectrocluster" | "edgehost",
  objectUid: string,
  params?: EventsComponentsObjTypeUidListParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.spectrocloud.com/v1/events/components/${objectKind}/${objectUid}?${stringifiedParams}`
    : `https://api.spectrocloud.com/v1/events/components/${objectKind}/${objectUid}`;
};

export const eventsComponentsObjTypeUidList = async (
  objectKind: "spectrocluster" | "edgehost",
  objectUid: string,
  params?: EventsComponentsObjTypeUidListParams,
  options?: RequestInit,
): Promise<eventsComponentsObjTypeUidListResponse> => {
  return customInstance<eventsComponentsObjTypeUidListResponse>(
    getEventsComponentsObjTypeUidListUrl(objectKind, objectUid, params),
    {
      ...options,
      method: "GET",
    },
  );
};
