/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type {
  ApiKey,
  ApiKeyCreateResponse,
  ApiKeyEntity,
  ApiKeyUpdate,
  ApiKeys,
  V1ApiKeyActiveStateBody,
} from ".././schemas";

import { customInstance } from ".././httpClient/customClient";

/**
 * @summary Retrieves a list of API keys
 */
export type apiKeysListResponse200 = {
  data: ApiKeys;
  status: 200;
};

export type apiKeysListResponseComposite = apiKeysListResponse200;

export type apiKeysListResponse = apiKeysListResponseComposite & {
  headers: Headers;
};

export const getApiKeysListUrl = () => {
  return `https://api.spectrocloud.com/v1/apiKeys`;
};

export const apiKeysList = async (
  options?: RequestInit,
): Promise<apiKeysListResponse> => {
  return customInstance<apiKeysListResponse>(getApiKeysListUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create an API key
 */
export type apiKeysCreateResponse201 = {
  data: ApiKeyCreateResponse;
  status: 201;
};

export type apiKeysCreateResponseComposite = apiKeysCreateResponse201;

export type apiKeysCreateResponse = apiKeysCreateResponseComposite & {
  headers: Headers;
};

export const getApiKeysCreateUrl = () => {
  return `https://api.spectrocloud.com/v1/apiKeys`;
};

export const apiKeysCreate = async (
  apiKeyEntity: ApiKeyEntity,
  options?: RequestInit,
): Promise<apiKeysCreateResponse> => {
  return customInstance<apiKeysCreateResponse>(getApiKeysCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(apiKeyEntity),
  });
};

/**
 * @summary Deletes the specified API key
 */
export type apiKeysUidDeleteResponse204 = {
  data: void;
  status: 204;
};

export type apiKeysUidDeleteResponseComposite = apiKeysUidDeleteResponse204;

export type apiKeysUidDeleteResponse = apiKeysUidDeleteResponseComposite & {
  headers: Headers;
};

export const getApiKeysUidDeleteUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/apiKeys/${uid}`;
};

export const apiKeysUidDelete = async (
  uid: string,
  options?: RequestInit,
): Promise<apiKeysUidDeleteResponse> => {
  return customInstance<apiKeysUidDeleteResponse>(getApiKeysUidDeleteUrl(uid), {
    ...options,
    method: "DELETE",
  });
};

/**
 * @summary Returns the specified API key
 */
export type apiKeysUidGetResponse200 = {
  data: ApiKey;
  status: 200;
};

export type apiKeysUidGetResponseComposite = apiKeysUidGetResponse200;

export type apiKeysUidGetResponse = apiKeysUidGetResponseComposite & {
  headers: Headers;
};

export const getApiKeysUidGetUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/apiKeys/${uid}`;
};

export const apiKeysUidGet = async (
  uid: string,
  options?: RequestInit,
): Promise<apiKeysUidGetResponse> => {
  return customInstance<apiKeysUidGetResponse>(getApiKeysUidGetUrl(uid), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Activate or de-active the specified API key
 */
export type apiKeysUidActiveStateResponse204 = {
  data: void;
  status: 204;
};

export type apiKeysUidActiveStateResponseComposite =
  apiKeysUidActiveStateResponse204;

export type apiKeysUidActiveStateResponse =
  apiKeysUidActiveStateResponseComposite & {
    headers: Headers;
  };

export const getApiKeysUidActiveStateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/apiKeys/${uid}`;
};

export const apiKeysUidActiveState = async (
  uid: string,
  v1ApiKeyActiveStateBody: V1ApiKeyActiveStateBody,
  options?: RequestInit,
): Promise<apiKeysUidActiveStateResponse> => {
  return customInstance<apiKeysUidActiveStateResponse>(
    getApiKeysUidActiveStateUrl(uid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1ApiKeyActiveStateBody),
    },
  );
};

/**
 * @summary Update the specified API key
 */
export type apiKeysUidUpdateResponse204 = {
  data: void;
  status: 204;
};

export type apiKeysUidUpdateResponseComposite = apiKeysUidUpdateResponse204;

export type apiKeysUidUpdateResponse = apiKeysUidUpdateResponseComposite & {
  headers: Headers;
};

export const getApiKeysUidUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/apiKeys/${uid}`;
};

export const apiKeysUidUpdate = async (
  uid: string,
  apiKeyUpdate: ApiKeyUpdate,
  options?: RequestInit,
): Promise<apiKeysUidUpdateResponse> => {
  return customInstance<apiKeysUidUpdateResponse>(getApiKeysUidUpdateUrl(uid), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(apiKeyUpdate),
  });
};

/**
 * @summary Revoke or re-activate the API key access
 */
export type apiKeysUidStateResponse204 = {
  data: void;
  status: 204;
};

export type apiKeysUidStateResponseComposite = apiKeysUidStateResponse204;

export type apiKeysUidStateResponse = apiKeysUidStateResponseComposite & {
  headers: Headers;
};

export const getApiKeysUidStateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/apiKeys/${uid}/state`;
};

export const apiKeysUidState = async (
  uid: string,
  v1ApiKeyActiveStateBody: V1ApiKeyActiveStateBody,
  options?: RequestInit,
): Promise<apiKeysUidStateResponse> => {
  return customInstance<apiKeysUidStateResponse>(getApiKeysUidStateUrl(uid), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(v1ApiKeyActiveStateBody),
  });
};
