/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type {
  SystemReverseProxy,
  Updated,
  V1PasswordsBlockListBody,
} from ".././schemas";

import { customInstance } from ".././httpClient/customClient";

/**
 * @summary get the system config reverse proxy
 */
export type v1SystemConfigReverseProxyGetResponse200 = {
  data: SystemReverseProxy;
  status: 200;
};

export type v1SystemConfigReverseProxyGetResponseComposite =
  v1SystemConfigReverseProxyGetResponse200;

export type v1SystemConfigReverseProxyGetResponse =
  v1SystemConfigReverseProxyGetResponseComposite & {
    headers: Headers;
  };

export const getV1SystemConfigReverseProxyGetUrl = () => {
  return `https://api.spectrocloud.com/v1/system/config/reverseproxy`;
};

export const v1SystemConfigReverseProxyGet = async (
  options?: RequestInit,
): Promise<v1SystemConfigReverseProxyGetResponse> => {
  return customInstance<v1SystemConfigReverseProxyGetResponse>(
    getV1SystemConfigReverseProxyGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary updates the system config reverse proxy
 */
export type v1SystemConfigReverseProxyUpdateResponse204 = {
  data: Updated;
  status: 204;
};

export type v1SystemConfigReverseProxyUpdateResponseComposite =
  v1SystemConfigReverseProxyUpdateResponse204;

export type v1SystemConfigReverseProxyUpdateResponse =
  v1SystemConfigReverseProxyUpdateResponseComposite & {
    headers: Headers;
  };

export const getV1SystemConfigReverseProxyUpdateUrl = () => {
  return `https://api.spectrocloud.com/v1/system/config/reverseproxy`;
};

export const v1SystemConfigReverseProxyUpdate = async (
  systemReverseProxy: SystemReverseProxy,
  options?: RequestInit,
): Promise<v1SystemConfigReverseProxyUpdateResponse> => {
  return customInstance<v1SystemConfigReverseProxyUpdateResponse>(
    getV1SystemConfigReverseProxyUpdateUrl(),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(systemReverseProxy),
    },
  );
};

/**
 * @summary Delete a list of block listed passwords
 */
export type v1PasswordsBlockListDeleteResponse204 = {
  data: void;
  status: 204;
};

export type v1PasswordsBlockListDeleteResponseComposite =
  v1PasswordsBlockListDeleteResponse204;

export type v1PasswordsBlockListDeleteResponse =
  v1PasswordsBlockListDeleteResponseComposite & {
    headers: Headers;
  };

export const getV1PasswordsBlockListDeleteUrl = () => {
  return `https://api.spectrocloud.com/v1/system/passwords/blocklist`;
};

export const v1PasswordsBlockListDelete = async (
  v1PasswordsBlockListBody: V1PasswordsBlockListBody,
  options?: RequestInit,
): Promise<v1PasswordsBlockListDeleteResponse> => {
  return customInstance<v1PasswordsBlockListDeleteResponse>(
    getV1PasswordsBlockListDeleteUrl(),
    {
      ...options,
      method: "DELETE",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1PasswordsBlockListBody),
    },
  );
};

/**
 * @summary List of block listed passwords
 */
export type v1PasswordsBlockListUpdateResponse204 = {
  data: Updated;
  status: 204;
};

export type v1PasswordsBlockListUpdateResponseComposite =
  v1PasswordsBlockListUpdateResponse204;

export type v1PasswordsBlockListUpdateResponse =
  v1PasswordsBlockListUpdateResponseComposite & {
    headers: Headers;
  };

export const getV1PasswordsBlockListUpdateUrl = () => {
  return `https://api.spectrocloud.com/v1/system/passwords/blocklist`;
};

export const v1PasswordsBlockListUpdate = async (
  v1PasswordsBlockListBody: V1PasswordsBlockListBody,
  options?: RequestInit,
): Promise<v1PasswordsBlockListUpdateResponse> => {
  return customInstance<v1PasswordsBlockListUpdateResponse>(
    getV1PasswordsBlockListUpdateUrl(),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1PasswordsBlockListBody),
    },
  );
};
