/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.6
 * OpenAPI spec version: v1
 */
import type {
  AuthTokenRevoke,
  Macros,
  ProjectRolesEntity,
  ResourceRoles,
  SystemFeatures,
  SystemScarSpec,
  Uid,
  User,
  UserAssetSsh,
  UserAssetSshEntity,
  UserAssetsLocationAzure,
  UserAssetsLocationGcp,
  UserAssetsLocationS3,
  UserAssetsLocations,
  UserAssetsSsh,
  UserEntity,
  UserInfo,
  UserKubectlSession,
  UserPatch,
  UserRoleUIDs,
  UserRolesEntity,
  UserStatusLoginMode,
  UserUpdateEntity,
  Users,
  UsersAssetsLocationGetParams,
  UsersAssetsSshGetParams,
  UsersEmailPasswordResetBody,
  UsersListParams,
  UsersMetadata,
  UsersSummaryList,
  UsersSummarySpec,
  UsersUidPasswordChangeBody,
  V1MacrosBody,
  V1ProjectRolesPatchBody,
  V1ResourceRolesUpdateEntityBody,
  V1UserAssetsLocationAzureBody,
  V1UserAssetsLocationGcpBody,
  V1UserAssetsLocationS3Body,
  V1UsersPasswordChangeBody,
  V1VsphereDnsMappingBody,
  VsphereDnsMapping,
  VsphereDnsMappings,
  VsphereDnsMappingsGetParams,
  VsphereMappingGetParams,
} from ".././schemas";

import { customInstance } from ".././httpClient/customClient";

/**
 * Lists users the given user context
 * @summary Lists users
 */
export type usersListResponse200 = {
  data: Users;
  status: 200;
};

export type usersListResponseComposite = usersListResponse200;

export type usersListResponse = usersListResponseComposite & {
  headers: Headers;
};

export const getUsersListUrl = (params?: UsersListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.spectrocloud.com/v1/users?${stringifiedParams}`
    : `https://api.spectrocloud.com/v1/users`;
};

export const usersList = async (
  params?: UsersListParams,
  options?: RequestInit,
): Promise<usersListResponse> => {
  return customInstance<usersListResponse>(getUsersListUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * A user is created for the given user context
 * @summary Create User
 */
export type usersCreateResponse201 = {
  data: Uid;
  status: 201;
};

export type usersCreateResponseComposite = usersCreateResponse201;

export type usersCreateResponse = usersCreateResponseComposite & {
  headers: Headers;
};

export const getUsersCreateUrl = () => {
  return `https://api.spectrocloud.com/v1/users`;
};

export const usersCreate = async (
  userEntity: UserEntity,
  options?: RequestInit,
): Promise<usersCreateResponse> => {
  return customInstance<usersCreateResponse>(getUsersCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userEntity),
  });
};

/**
 * @summary Returns the specified users location
 */
export type usersAssetsLocationGetResponse200 = {
  data: UserAssetsLocations;
  status: 200;
};

export type usersAssetsLocationGetResponseComposite =
  usersAssetsLocationGetResponse200;

export type usersAssetsLocationGetResponse =
  usersAssetsLocationGetResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationGetUrl = (
  params?: UsersAssetsLocationGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.spectrocloud.com/v1/users/assets/locations?${stringifiedParams}`
    : `https://api.spectrocloud.com/v1/users/assets/locations`;
};

export const usersAssetsLocationGet = async (
  params?: UsersAssetsLocationGetParams,
  options?: RequestInit,
): Promise<usersAssetsLocationGetResponse> => {
  return customInstance<usersAssetsLocationGetResponse>(
    getUsersAssetsLocationGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Create a Azure location
 */
export type usersAssetsLocationAzureCreateResponse201 = {
  data: Uid;
  status: 201;
};

export type usersAssetsLocationAzureCreateResponseComposite =
  usersAssetsLocationAzureCreateResponse201;

export type usersAssetsLocationAzureCreateResponse =
  usersAssetsLocationAzureCreateResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationAzureCreateUrl = () => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/azure`;
};

export const usersAssetsLocationAzureCreate = async (
  v1UserAssetsLocationAzureBody: V1UserAssetsLocationAzureBody,
  options?: RequestInit,
): Promise<usersAssetsLocationAzureCreateResponse> => {
  return customInstance<usersAssetsLocationAzureCreateResponse>(
    getUsersAssetsLocationAzureCreateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1UserAssetsLocationAzureBody),
    },
  );
};

/**
 * @summary Returns the specified Azure location
 */
export type usersAssetsLocationAzureGetResponse200 = {
  data: UserAssetsLocationAzure;
  status: 200;
};

export type usersAssetsLocationAzureGetResponseComposite =
  usersAssetsLocationAzureGetResponse200;

export type usersAssetsLocationAzureGetResponse =
  usersAssetsLocationAzureGetResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationAzureGetUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/azure/${uid}`;
};

export const usersAssetsLocationAzureGet = async (
  uid: string,
  options?: RequestInit,
): Promise<usersAssetsLocationAzureGetResponse> => {
  return customInstance<usersAssetsLocationAzureGetResponse>(
    getUsersAssetsLocationAzureGetUrl(uid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Updates the specified Azure location
 */
export type usersAssetsLocationAzureUpdateResponse204 = {
  data: void;
  status: 204;
};

export type usersAssetsLocationAzureUpdateResponseComposite =
  usersAssetsLocationAzureUpdateResponse204;

export type usersAssetsLocationAzureUpdateResponse =
  usersAssetsLocationAzureUpdateResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationAzureUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/azure/${uid}`;
};

export const usersAssetsLocationAzureUpdate = async (
  uid: string,
  v1UserAssetsLocationAzureBody: V1UserAssetsLocationAzureBody,
  options?: RequestInit,
): Promise<usersAssetsLocationAzureUpdateResponse> => {
  return customInstance<usersAssetsLocationAzureUpdateResponse>(
    getUsersAssetsLocationAzureUpdateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1UserAssetsLocationAzureBody),
    },
  );
};

/**
 * @summary Create a GCP location
 */
export type usersAssetsLocationGcpCreateResponse201 = {
  data: Uid;
  status: 201;
};

export type usersAssetsLocationGcpCreateResponseComposite =
  usersAssetsLocationGcpCreateResponse201;

export type usersAssetsLocationGcpCreateResponse =
  usersAssetsLocationGcpCreateResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationGcpCreateUrl = () => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/gcp`;
};

export const usersAssetsLocationGcpCreate = async (
  v1UserAssetsLocationGcpBody: V1UserAssetsLocationGcpBody,
  options?: RequestInit,
): Promise<usersAssetsLocationGcpCreateResponse> => {
  return customInstance<usersAssetsLocationGcpCreateResponse>(
    getUsersAssetsLocationGcpCreateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1UserAssetsLocationGcpBody),
    },
  );
};

/**
 * @summary Returns the specified GCP location
 */
export type usersAssetsLocationGcpGetResponse200 = {
  data: UserAssetsLocationGcp;
  status: 200;
};

export type usersAssetsLocationGcpGetResponseComposite =
  usersAssetsLocationGcpGetResponse200;

export type usersAssetsLocationGcpGetResponse =
  usersAssetsLocationGcpGetResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationGcpGetUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/gcp/${uid}`;
};

export const usersAssetsLocationGcpGet = async (
  uid: string,
  options?: RequestInit,
): Promise<usersAssetsLocationGcpGetResponse> => {
  return customInstance<usersAssetsLocationGcpGetResponse>(
    getUsersAssetsLocationGcpGetUrl(uid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Updates the specified GCP location
 */
export type usersAssetsLocationGcpUpdateResponse204 = {
  data: void;
  status: 204;
};

export type usersAssetsLocationGcpUpdateResponseComposite =
  usersAssetsLocationGcpUpdateResponse204;

export type usersAssetsLocationGcpUpdateResponse =
  usersAssetsLocationGcpUpdateResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationGcpUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/gcp/${uid}`;
};

export const usersAssetsLocationGcpUpdate = async (
  uid: string,
  v1UserAssetsLocationGcpBody: V1UserAssetsLocationGcpBody,
  options?: RequestInit,
): Promise<usersAssetsLocationGcpUpdateResponse> => {
  return customInstance<usersAssetsLocationGcpUpdateResponse>(
    getUsersAssetsLocationGcpUpdateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1UserAssetsLocationGcpBody),
    },
  );
};

/**
 * @summary Create a MinIO location
 */
export type usersAssetsLocationMinioCreateResponse201 = {
  data: Uid;
  status: 201;
};

export type usersAssetsLocationMinioCreateResponseComposite =
  usersAssetsLocationMinioCreateResponse201;

export type usersAssetsLocationMinioCreateResponse =
  usersAssetsLocationMinioCreateResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationMinioCreateUrl = () => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/minio`;
};

export const usersAssetsLocationMinioCreate = async (
  v1UserAssetsLocationS3Body: V1UserAssetsLocationS3Body,
  options?: RequestInit,
): Promise<usersAssetsLocationMinioCreateResponse> => {
  return customInstance<usersAssetsLocationMinioCreateResponse>(
    getUsersAssetsLocationMinioCreateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1UserAssetsLocationS3Body),
    },
  );
};

/**
 * @summary Returns the specified MinIO location
 */
export type usersAssetsLocationMinioGetResponse200 = {
  data: UserAssetsLocationS3;
  status: 200;
};

export type usersAssetsLocationMinioGetResponseComposite =
  usersAssetsLocationMinioGetResponse200;

export type usersAssetsLocationMinioGetResponse =
  usersAssetsLocationMinioGetResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationMinioGetUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/minio/${uid}`;
};

export const usersAssetsLocationMinioGet = async (
  uid: string,
  options?: RequestInit,
): Promise<usersAssetsLocationMinioGetResponse> => {
  return customInstance<usersAssetsLocationMinioGetResponse>(
    getUsersAssetsLocationMinioGetUrl(uid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Updates the specified MinIO location
 */
export type usersAssetsLocationMinioUpdateResponse204 = {
  data: void;
  status: 204;
};

export type usersAssetsLocationMinioUpdateResponseComposite =
  usersAssetsLocationMinioUpdateResponse204;

export type usersAssetsLocationMinioUpdateResponse =
  usersAssetsLocationMinioUpdateResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationMinioUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/minio/${uid}`;
};

export const usersAssetsLocationMinioUpdate = async (
  uid: string,
  v1UserAssetsLocationS3Body: V1UserAssetsLocationS3Body,
  options?: RequestInit,
): Promise<usersAssetsLocationMinioUpdateResponse> => {
  return customInstance<usersAssetsLocationMinioUpdateResponse>(
    getUsersAssetsLocationMinioUpdateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1UserAssetsLocationS3Body),
    },
  );
};

/**
 * @summary Create a S3 location
 */
export type usersAssetsLocationS3CreateResponse201 = {
  data: Uid;
  status: 201;
};

export type usersAssetsLocationS3CreateResponseComposite =
  usersAssetsLocationS3CreateResponse201;

export type usersAssetsLocationS3CreateResponse =
  usersAssetsLocationS3CreateResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationS3CreateUrl = () => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/s3`;
};

export const usersAssetsLocationS3Create = async (
  v1UserAssetsLocationS3Body: V1UserAssetsLocationS3Body,
  options?: RequestInit,
): Promise<usersAssetsLocationS3CreateResponse> => {
  return customInstance<usersAssetsLocationS3CreateResponse>(
    getUsersAssetsLocationS3CreateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1UserAssetsLocationS3Body),
    },
  );
};

/**
 * @summary Returns the specified S3 location
 */
export type usersAssetsLocationS3DeleteResponse204 = {
  data: void;
  status: 204;
};

export type usersAssetsLocationS3DeleteResponseComposite =
  usersAssetsLocationS3DeleteResponse204;

export type usersAssetsLocationS3DeleteResponse =
  usersAssetsLocationS3DeleteResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationS3DeleteUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/s3/${uid}`;
};

export const usersAssetsLocationS3Delete = async (
  uid: string,
  options?: RequestInit,
): Promise<usersAssetsLocationS3DeleteResponse> => {
  return customInstance<usersAssetsLocationS3DeleteResponse>(
    getUsersAssetsLocationS3DeleteUrl(uid),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Returns the specified S3 location
 */
export type usersAssetsLocationS3GetResponse200 = {
  data: UserAssetsLocationS3;
  status: 200;
};

export type usersAssetsLocationS3GetResponseComposite =
  usersAssetsLocationS3GetResponse200;

export type usersAssetsLocationS3GetResponse =
  usersAssetsLocationS3GetResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationS3GetUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/s3/${uid}`;
};

export const usersAssetsLocationS3Get = async (
  uid: string,
  options?: RequestInit,
): Promise<usersAssetsLocationS3GetResponse> => {
  return customInstance<usersAssetsLocationS3GetResponse>(
    getUsersAssetsLocationS3GetUrl(uid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Updates the specified S3 location
 */
export type usersAssetsLocationS3UpdateResponse204 = {
  data: void;
  status: 204;
};

export type usersAssetsLocationS3UpdateResponseComposite =
  usersAssetsLocationS3UpdateResponse204;

export type usersAssetsLocationS3UpdateResponse =
  usersAssetsLocationS3UpdateResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationS3UpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/s3/${uid}`;
};

export const usersAssetsLocationS3Update = async (
  uid: string,
  v1UserAssetsLocationS3Body: V1UserAssetsLocationS3Body,
  options?: RequestInit,
): Promise<usersAssetsLocationS3UpdateResponse> => {
  return customInstance<usersAssetsLocationS3UpdateResponse>(
    getUsersAssetsLocationS3UpdateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1UserAssetsLocationS3Body),
    },
  );
};

/**
 * @summary Update the default backup location
 */
export type usersAssetsLocationDefaultUpdateResponse204 = {
  data: void;
  status: 204;
};

export type usersAssetsLocationDefaultUpdateResponseComposite =
  usersAssetsLocationDefaultUpdateResponse204;

export type usersAssetsLocationDefaultUpdateResponse =
  usersAssetsLocationDefaultUpdateResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationDefaultUpdateUrl = (
  type: string,
  uid: string,
) => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/${type}/${uid}/default`;
};

export const usersAssetsLocationDefaultUpdate = async (
  type: string,
  uid: string,
  options?: RequestInit,
): Promise<usersAssetsLocationDefaultUpdateResponse> => {
  return customInstance<usersAssetsLocationDefaultUpdateResponse>(
    getUsersAssetsLocationDefaultUpdateUrl(type, uid),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * @summary Deletes the specified location
 */
export type usersAssetsLocationDeleteResponse204 = {
  data: void;
  status: 204;
};

export type usersAssetsLocationDeleteResponseComposite =
  usersAssetsLocationDeleteResponse204;

export type usersAssetsLocationDeleteResponse =
  usersAssetsLocationDeleteResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetsLocationDeleteUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/locations/${uid}`;
};

export const usersAssetsLocationDelete = async (
  uid: string,
  options?: RequestInit,
): Promise<usersAssetsLocationDeleteResponse> => {
  return customInstance<usersAssetsLocationDeleteResponse>(
    getUsersAssetsLocationDeleteUrl(uid),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Returns the SSH keys
 */
export type usersAssetsSshGetResponse200 = {
  data: UserAssetsSsh;
  status: 200;
};

export type usersAssetsSshGetResponseComposite = usersAssetsSshGetResponse200;

export type usersAssetsSshGetResponse = usersAssetsSshGetResponseComposite & {
  headers: Headers;
};

export const getUsersAssetsSshGetUrl = (params?: UsersAssetsSshGetParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.spectrocloud.com/v1/users/assets/sshkeys?${stringifiedParams}`
    : `https://api.spectrocloud.com/v1/users/assets/sshkeys`;
};

export const usersAssetsSshGet = async (
  params?: UsersAssetsSshGetParams,
  options?: RequestInit,
): Promise<usersAssetsSshGetResponse> => {
  return customInstance<usersAssetsSshGetResponse>(
    getUsersAssetsSshGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Creates a SSH key
 */
export type userAssetsSshCreateResponse201 = {
  data: Uid;
  status: 201;
};

export type userAssetsSshCreateResponseComposite =
  userAssetsSshCreateResponse201;

export type userAssetsSshCreateResponse =
  userAssetsSshCreateResponseComposite & {
    headers: Headers;
  };

export const getUserAssetsSshCreateUrl = () => {
  return `https://api.spectrocloud.com/v1/users/assets/sshkeys`;
};

export const userAssetsSshCreate = async (
  userAssetSshEntity: UserAssetSshEntity,
  options?: RequestInit,
): Promise<userAssetsSshCreateResponse> => {
  return customInstance<userAssetsSshCreateResponse>(
    getUserAssetsSshCreateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userAssetSshEntity),
    },
  );
};

/**
 * @summary Returns the specified user ssh key
 */
export type usersAssetSshDeleteResponse204 = {
  data: void;
  status: 204;
};

export type usersAssetSshDeleteResponseComposite =
  usersAssetSshDeleteResponse204;

export type usersAssetSshDeleteResponse =
  usersAssetSshDeleteResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetSshDeleteUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/sshkeys/${uid}`;
};

export const usersAssetSshDelete = async (
  uid: string,
  options?: RequestInit,
): Promise<usersAssetSshDeleteResponse> => {
  return customInstance<usersAssetSshDeleteResponse>(
    getUsersAssetSshDeleteUrl(uid),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Returns the specified user ssh key
 */
export type usersAssetSshGetUidResponse200 = {
  data: UserAssetSsh;
  status: 200;
};

export type usersAssetSshGetUidResponseComposite =
  usersAssetSshGetUidResponse200;

export type usersAssetSshGetUidResponse =
  usersAssetSshGetUidResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetSshGetUidUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/sshkeys/${uid}`;
};

export const usersAssetSshGetUid = async (
  uid: string,
  options?: RequestInit,
): Promise<usersAssetSshGetUidResponse> => {
  return customInstance<usersAssetSshGetUidResponse>(
    getUsersAssetSshGetUidUrl(uid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Updates the specified user ssh key
 */
export type usersAssetSshUpdateResponse204 = {
  data: void;
  status: 204;
};

export type usersAssetSshUpdateResponseComposite =
  usersAssetSshUpdateResponse204;

export type usersAssetSshUpdateResponse =
  usersAssetSshUpdateResponseComposite & {
    headers: Headers;
  };

export const getUsersAssetSshUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/sshkeys/${uid}`;
};

export const usersAssetSshUpdate = async (
  uid: string,
  userAssetSsh: UserAssetSsh,
  options?: RequestInit,
): Promise<usersAssetSshUpdateResponse> => {
  return customInstance<usersAssetSshUpdateResponse>(
    getUsersAssetSshUpdateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userAssetSsh),
    },
  );
};

/**
 * @summary Returns the specified vSphere DNS mapping
 */
export type vsphereMappingGetResponse200 = {
  data: VsphereDnsMapping;
  status: 200;
};

export type vsphereMappingGetResponseComposite = vsphereMappingGetResponse200;

export type vsphereMappingGetResponse = vsphereMappingGetResponseComposite & {
  headers: Headers;
};

export const getVsphereMappingGetUrl = (params: VsphereMappingGetParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.spectrocloud.com/v1/users/assets/vsphere/dnsMapping?${stringifiedParams}`
    : `https://api.spectrocloud.com/v1/users/assets/vsphere/dnsMapping`;
};

export const vsphereMappingGet = async (
  params: VsphereMappingGetParams,
  options?: RequestInit,
): Promise<vsphereMappingGetResponse> => {
  return customInstance<vsphereMappingGetResponse>(
    getVsphereMappingGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Returns the specified vSphere DNS mappings
 */
export type vsphereDnsMappingsGetResponse200 = {
  data: VsphereDnsMappings;
  status: 200;
};

export type vsphereDnsMappingsGetResponseComposite =
  vsphereDnsMappingsGetResponse200;

export type vsphereDnsMappingsGetResponse =
  vsphereDnsMappingsGetResponseComposite & {
    headers: Headers;
  };

export const getVsphereDnsMappingsGetUrl = (
  params?: VsphereDnsMappingsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://api.spectrocloud.com/v1/users/assets/vsphere/dnsMappings?${stringifiedParams}`
    : `https://api.spectrocloud.com/v1/users/assets/vsphere/dnsMappings`;
};

export const vsphereDnsMappingsGet = async (
  params?: VsphereDnsMappingsGetParams,
  options?: RequestInit,
): Promise<vsphereDnsMappingsGetResponse> => {
  return customInstance<vsphereDnsMappingsGetResponse>(
    getVsphereDnsMappingsGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Create a vSphere DNS mapping
 */
export type vsphereDnsMappingCreateResponse201 = {
  data: Uid;
  status: 201;
};

export type vsphereDnsMappingCreateResponseComposite =
  vsphereDnsMappingCreateResponse201;

export type vsphereDnsMappingCreateResponse =
  vsphereDnsMappingCreateResponseComposite & {
    headers: Headers;
  };

export const getVsphereDnsMappingCreateUrl = () => {
  return `https://api.spectrocloud.com/v1/users/assets/vsphere/dnsMappings`;
};

export const vsphereDnsMappingCreate = async (
  v1VsphereDnsMappingBody: V1VsphereDnsMappingBody,
  options?: RequestInit,
): Promise<vsphereDnsMappingCreateResponse> => {
  return customInstance<vsphereDnsMappingCreateResponse>(
    getVsphereDnsMappingCreateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1VsphereDnsMappingBody),
    },
  );
};

/**
 * @summary Deletes the specified vSphere DNS mapping
 */
export type vsphereDnsMappingDeleteResponse204 = {
  data: void;
  status: 204;
};

export type vsphereDnsMappingDeleteResponseComposite =
  vsphereDnsMappingDeleteResponse204;

export type vsphereDnsMappingDeleteResponse =
  vsphereDnsMappingDeleteResponseComposite & {
    headers: Headers;
  };

export const getVsphereDnsMappingDeleteUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/vsphere/dnsMappings/${uid}`;
};

export const vsphereDnsMappingDelete = async (
  uid: string,
  options?: RequestInit,
): Promise<vsphereDnsMappingDeleteResponse> => {
  return customInstance<vsphereDnsMappingDeleteResponse>(
    getVsphereDnsMappingDeleteUrl(uid),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Returns the specified vSphere DNS mapping
 */
export type vsphereDnsMappingGetResponse200 = {
  data: VsphereDnsMapping;
  status: 200;
};

export type vsphereDnsMappingGetResponseComposite =
  vsphereDnsMappingGetResponse200;

export type vsphereDnsMappingGetResponse =
  vsphereDnsMappingGetResponseComposite & {
    headers: Headers;
  };

export const getVsphereDnsMappingGetUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/vsphere/dnsMappings/${uid}`;
};

export const vsphereDnsMappingGet = async (
  uid: string,
  options?: RequestInit,
): Promise<vsphereDnsMappingGetResponse> => {
  return customInstance<vsphereDnsMappingGetResponse>(
    getVsphereDnsMappingGetUrl(uid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Updates the specified vSphere DNS mapping
 */
export type vsphereDnsMappingUpdateResponse204 = {
  data: void;
  status: 204;
};

export type vsphereDnsMappingUpdateResponseComposite =
  vsphereDnsMappingUpdateResponse204;

export type vsphereDnsMappingUpdateResponse =
  vsphereDnsMappingUpdateResponseComposite & {
    headers: Headers;
  };

export const getVsphereDnsMappingUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/assets/vsphere/dnsMappings/${uid}`;
};

export const vsphereDnsMappingUpdate = async (
  uid: string,
  v1VsphereDnsMappingBody: V1VsphereDnsMappingBody,
  options?: RequestInit,
): Promise<vsphereDnsMappingUpdateResponse> => {
  return customInstance<vsphereDnsMappingUpdateResponse>(
    getVsphereDnsMappingUpdateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1VsphereDnsMappingBody),
    },
  );
};

/**
 * @summary Revoke access of specific token(s)
 */
export type usersAuthTokensRevokeResponse204 = {
  data: void;
  status: 204;
};

export type usersAuthTokensRevokeResponseComposite =
  usersAuthTokensRevokeResponse204;

export type usersAuthTokensRevokeResponse =
  usersAuthTokensRevokeResponseComposite & {
    headers: Headers;
  };

export const getUsersAuthTokensRevokeUrl = () => {
  return `https://api.spectrocloud.com/v1/users/auth/tokens/revoke`;
};

export const usersAuthTokensRevoke = async (
  authTokenRevoke: AuthTokenRevoke,
  options?: RequestInit,
): Promise<usersAuthTokensRevokeResponse> => {
  return customInstance<usersAuthTokensRevokeResponse>(
    getUsersAuthTokensRevokeUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(authTokenRevoke),
    },
  );
};

/**
 * @summary Get the system Spectro repository. Restricted to edge services
 */
export type v1UsersConfigScarGetResponse200 = {
  data: SystemScarSpec;
  status: 200;
};

export type v1UsersConfigScarGetResponseComposite =
  v1UsersConfigScarGetResponse200;

export type v1UsersConfigScarGetResponse =
  v1UsersConfigScarGetResponseComposite & {
    headers: Headers;
  };

export const getV1UsersConfigScarGetUrl = () => {
  return `https://api.spectrocloud.com/v1/users/config/scar`;
};

export const v1UsersConfigScarGet = async (
  options?: RequestInit,
): Promise<v1UsersConfigScarGetResponse> => {
  return customInstance<v1UsersConfigScarGetResponse>(
    getV1UsersConfigScarGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Returns a basic information of User for the specified uid.
 * @summary Returns the base information of specified User
 */
export type usersInfoGetResponse200 = {
  data: UserInfo;
  status: 200;
};

export type usersInfoGetResponseComposite = usersInfoGetResponse200;

export type usersInfoGetResponse = usersInfoGetResponseComposite & {
  headers: Headers;
};

export const getUsersInfoGetUrl = () => {
  return `https://api.spectrocloud.com/v1/users/info`;
};

export const usersInfoGet = async (
  options?: RequestInit,
): Promise<usersInfoGetResponse> => {
  return customInstance<usersInfoGetResponse>(getUsersInfoGetUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * gets users kubectl session
 * @summary gets users kubectl session
 */
export type v1UsersKubectlSessionUidResponse200 = {
  data: UserKubectlSession;
  status: 200;
};

export type v1UsersKubectlSessionUidResponseComposite =
  v1UsersKubectlSessionUidResponse200;

export type v1UsersKubectlSessionUidResponse =
  v1UsersKubectlSessionUidResponseComposite & {
    headers: Headers;
  };

export const getV1UsersKubectlSessionUidUrl = (sessionUid: string) => {
  return `https://api.spectrocloud.com/v1/users/kubectl/session/${sessionUid}`;
};

export const v1UsersKubectlSessionUid = async (
  sessionUid: string,
  options?: RequestInit,
): Promise<v1UsersKubectlSessionUidResponse> => {
  return customInstance<v1UsersKubectlSessionUidResponse>(
    getV1UsersKubectlSessionUidUrl(sessionUid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Retrieves a list of users metadata
 */
export type usersMetadataResponse200 = {
  data: UsersMetadata;
  status: 200;
};

export type usersMetadataResponseComposite = usersMetadataResponse200;

export type usersMetadataResponse = usersMetadataResponseComposite & {
  headers: Headers;
};

export const getUsersMetadataUrl = () => {
  return `https://api.spectrocloud.com/v1/users/meta`;
};

export const usersMetadata = async (
  options?: RequestInit,
): Promise<usersMetadataResponse> => {
  return customInstance<usersMetadataResponse>(getUsersMetadataUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * User password change request via current password and emailId
 * @summary User password change request using the user emailId
 */
export type v1UsersPasswordChangeResponse204 = {
  data: void;
  status: 204;
};

export type v1UsersPasswordChangeResponseComposite =
  v1UsersPasswordChangeResponse204;

export type v1UsersPasswordChangeResponse =
  v1UsersPasswordChangeResponseComposite & {
    headers: Headers;
  };

export const getV1UsersPasswordChangeUrl = () => {
  return `https://api.spectrocloud.com/v1/users/password/change`;
};

export const v1UsersPasswordChange = async (
  v1UsersPasswordChangeBody: V1UsersPasswordChangeBody,
  options?: RequestInit,
): Promise<v1UsersPasswordChangeResponse> => {
  return customInstance<v1UsersPasswordChangeResponse>(
    getV1UsersPasswordChangeUrl(),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1UsersPasswordChangeBody),
    },
  );
};

/**
 * User password request will be sent to the supplied emailId
 * @summary User password reset request using the email id
 */
export type usersEmailPasswordResetResponse204 = {
  data: void;
  status: 204;
};

export type usersEmailPasswordResetResponseComposite =
  usersEmailPasswordResetResponse204;

export type usersEmailPasswordResetResponse =
  usersEmailPasswordResetResponseComposite & {
    headers: Headers;
  };

export const getUsersEmailPasswordResetUrl = () => {
  return `https://api.spectrocloud.com/v1/users/password/reset`;
};

export const usersEmailPasswordReset = async (
  usersEmailPasswordResetBody: UsersEmailPasswordResetBody,
  options?: RequestInit,
): Promise<usersEmailPasswordResetResponse> => {
  return customInstance<usersEmailPasswordResetResponse>(
    getUsersEmailPasswordResetUrl(),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(usersEmailPasswordResetBody),
    },
  );
};

/**
 * @summary Retrieves a list of users summary with provided filter spec
 */
export type usersSummaryGetResponse200 = {
  data: UsersSummaryList;
  status: 200;
};

export type usersSummaryGetResponseComposite = usersSummaryGetResponse200;

export type usersSummaryGetResponse = usersSummaryGetResponseComposite & {
  headers: Headers;
};

export const getUsersSummaryGetUrl = () => {
  return `https://api.spectrocloud.com/v1/users/summary`;
};

export const usersSummaryGet = async (
  usersSummarySpec: UsersSummarySpec,
  options?: RequestInit,
): Promise<usersSummaryGetResponse> => {
  return customInstance<usersSummaryGetResponse>(getUsersSummaryGetUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(usersSummarySpec),
  });
};

/**
 * Returns the users system feature
 * @summary Returns the users system feature
 */
export type usersSystemFeatureResponse200 = {
  data: SystemFeatures;
  status: 200;
};

export type usersSystemFeatureResponseComposite = usersSystemFeatureResponse200;

export type usersSystemFeatureResponse = usersSystemFeatureResponseComposite & {
  headers: Headers;
};

export const getUsersSystemFeatureUrl = () => {
  return `https://api.spectrocloud.com/v1/users/system/features`;
};

export const usersSystemFeature = async (
  options?: RequestInit,
): Promise<usersSystemFeatureResponse> => {
  return customInstance<usersSystemFeatureResponse>(
    getUsersSystemFeatureUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Delete the macros for the system user by macro name
 */
export type usersSystemMacrosDeleteByMacroNameResponse204 = {
  data: void;
  status: 204;
};

export type usersSystemMacrosDeleteByMacroNameResponseComposite =
  usersSystemMacrosDeleteByMacroNameResponse204;

export type usersSystemMacrosDeleteByMacroNameResponse =
  usersSystemMacrosDeleteByMacroNameResponseComposite & {
    headers: Headers;
  };

export const getUsersSystemMacrosDeleteByMacroNameUrl = () => {
  return `https://api.spectrocloud.com/v1/users/system/macros`;
};

export const usersSystemMacrosDeleteByMacroName = async (
  v1MacrosBody: V1MacrosBody,
  options?: RequestInit,
): Promise<usersSystemMacrosDeleteByMacroNameResponse> => {
  return customInstance<usersSystemMacrosDeleteByMacroNameResponse>(
    getUsersSystemMacrosDeleteByMacroNameUrl(),
    {
      ...options,
      method: "DELETE",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1MacrosBody),
    },
  );
};

/**
 * @summary List the macros of the system
 */
export type usersSystemMacrosListResponse200 = {
  data: Macros;
  status: 200;
};

export type usersSystemMacrosListResponseComposite =
  usersSystemMacrosListResponse200;

export type usersSystemMacrosListResponse =
  usersSystemMacrosListResponseComposite & {
    headers: Headers;
  };

export const getUsersSystemMacrosListUrl = () => {
  return `https://api.spectrocloud.com/v1/users/system/macros`;
};

export const usersSystemMacrosList = async (
  options?: RequestInit,
): Promise<usersSystemMacrosListResponse> => {
  return customInstance<usersSystemMacrosListResponse>(
    getUsersSystemMacrosListUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update the macros for the system user by macro name
 */
export type usersSystemMacrosUpdateByMacroNameResponse204 = {
  data: void;
  status: 204;
};

export type usersSystemMacrosUpdateByMacroNameResponseComposite =
  usersSystemMacrosUpdateByMacroNameResponse204;

export type usersSystemMacrosUpdateByMacroNameResponse =
  usersSystemMacrosUpdateByMacroNameResponseComposite & {
    headers: Headers;
  };

export const getUsersSystemMacrosUpdateByMacroNameUrl = () => {
  return `https://api.spectrocloud.com/v1/users/system/macros`;
};

export const usersSystemMacrosUpdateByMacroName = async (
  v1MacrosBody: V1MacrosBody,
  options?: RequestInit,
): Promise<usersSystemMacrosUpdateByMacroNameResponse> => {
  return customInstance<usersSystemMacrosUpdateByMacroNameResponse>(
    getUsersSystemMacrosUpdateByMacroNameUrl(),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1MacrosBody),
    },
  );
};

/**
 * @summary Create or add new macros for the system user
 */
export type usersSystemMacrosCreateResponse204 = {
  data: void;
  status: 204;
};

export type usersSystemMacrosCreateResponseComposite =
  usersSystemMacrosCreateResponse204;

export type usersSystemMacrosCreateResponse =
  usersSystemMacrosCreateResponseComposite & {
    headers: Headers;
  };

export const getUsersSystemMacrosCreateUrl = () => {
  return `https://api.spectrocloud.com/v1/users/system/macros`;
};

export const usersSystemMacrosCreate = async (
  v1MacrosBody: V1MacrosBody,
  options?: RequestInit,
): Promise<usersSystemMacrosCreateResponse> => {
  return customInstance<usersSystemMacrosCreateResponse>(
    getUsersSystemMacrosCreateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1MacrosBody),
    },
  );
};

/**
 * @summary Update the macros of the system
 */
export type usersSystemMacrosUpdateResponse204 = {
  data: void;
  status: 204;
};

export type usersSystemMacrosUpdateResponseComposite =
  usersSystemMacrosUpdateResponse204;

export type usersSystemMacrosUpdateResponse =
  usersSystemMacrosUpdateResponseComposite & {
    headers: Headers;
  };

export const getUsersSystemMacrosUpdateUrl = () => {
  return `https://api.spectrocloud.com/v1/users/system/macros`;
};

export const usersSystemMacrosUpdate = async (
  v1MacrosBody: V1MacrosBody,
  options?: RequestInit,
): Promise<usersSystemMacrosUpdateResponse> => {
  return customInstance<usersSystemMacrosUpdateResponse>(
    getUsersSystemMacrosUpdateUrl(),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1MacrosBody),
    },
  );
};

/**
 * Deletes the specified User for given uid
 * @summary Deletes the specified User
 */
export type usersUidDeleteResponse204 = {
  data: void;
  status: 204;
};

export type usersUidDeleteResponseComposite = usersUidDeleteResponse204;

export type usersUidDeleteResponse = usersUidDeleteResponseComposite & {
  headers: Headers;
};

export const getUsersUidDeleteUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}`;
};

export const usersUidDelete = async (
  uid: string,
  options?: RequestInit,
): Promise<usersUidDeleteResponse> => {
  return customInstance<usersUidDeleteResponse>(getUsersUidDeleteUrl(uid), {
    ...options,
    method: "DELETE",
  });
};

/**
 * Returns a User for the specified uid.
 * @summary Returns the specified User
 */
export type usersUidGetResponse200 = {
  data: User;
  status: 200;
};

export type usersUidGetResponseComposite = usersUidGetResponse200;

export type usersUidGetResponse = usersUidGetResponseComposite & {
  headers: Headers;
};

export const getUsersUidGetUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}`;
};

export const usersUidGet = async (
  uid: string,
  options?: RequestInit,
): Promise<usersUidGetResponse> => {
  return customInstance<usersUidGetResponse>(getUsersUidGetUrl(uid), {
    ...options,
    method: "GET",
  });
};

/**
 * User is patched for the specified information
 * @summary Patches the specified User
 */
export type usersUidPatchResponse204 = {
  data: void;
  status: 204;
};

export type usersUidPatchResponseComposite = usersUidPatchResponse204;

export type usersUidPatchResponse = usersUidPatchResponseComposite & {
  headers: Headers;
};

export const getUsersUidPatchUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}`;
};

export const usersUidPatch = async (
  uid: string,
  userPatch: UserPatch,
  options?: RequestInit,
): Promise<usersUidPatchResponse> => {
  return customInstance<usersUidPatchResponse>(getUsersUidPatchUrl(uid), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userPatch),
  });
};

/**
 * A user is created for the given user context
 * @summary Update User
 */
export type usersUidUpdateResponse204 = {
  data: void;
  status: 204;
};

export type usersUidUpdateResponseComposite = usersUidUpdateResponse204;

export type usersUidUpdateResponse = usersUidUpdateResponseComposite & {
  headers: Headers;
};

export const getUsersUidUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}`;
};

export const usersUidUpdate = async (
  uid: string,
  userUpdateEntity: UserUpdateEntity,
  options?: RequestInit,
): Promise<usersUidUpdateResponse> => {
  return customInstance<usersUidUpdateResponse>(getUsersUidUpdateUrl(uid), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userUpdateEntity),
  });
};

/**
 * User password change request via current password
 * @summary User password change request using the user uid
 */
export type usersUidPasswordChangeResponse204 = {
  data: void;
  status: 204;
};

export type usersUidPasswordChangeResponseComposite =
  usersUidPasswordChangeResponse204;

export type usersUidPasswordChangeResponse =
  usersUidPasswordChangeResponseComposite & {
    headers: Headers;
  };

export const getUsersUidPasswordChangeUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}/password/change`;
};

export const usersUidPasswordChange = async (
  uid: string,
  usersUidPasswordChangeBody: UsersUidPasswordChangeBody,
  options?: RequestInit,
): Promise<usersUidPasswordChangeResponse> => {
  return customInstance<usersUidPasswordChangeResponse>(
    getUsersUidPasswordChangeUrl(uid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(usersUidPasswordChangeBody),
    },
  );
};

/**
 * User password reset request, will send the password reset option through the emailId
 * @summary User password reset request using the user uid
 */
export type usersUidPasswordResetResponse204 = {
  data: void;
  status: 204;
};

export type usersUidPasswordResetResponseComposite =
  usersUidPasswordResetResponse204;

export type usersUidPasswordResetResponse =
  usersUidPasswordResetResponseComposite & {
    headers: Headers;
  };

export const getUsersUidPasswordResetUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}/password/reset`;
};

export const usersUidPasswordReset = async (
  uid: string,
  options?: RequestInit,
): Promise<usersUidPasswordResetResponse> => {
  return customInstance<usersUidPasswordResetResponse>(
    getUsersUidPasswordResetUrl(uid),
    {
      ...options,
      method: "PATCH",
    },
  );
};

/**
 * Returns a User with projects and roles
 * @summary Returns the specified User Projects and Roles information
 */
export type usersProjectRolesResponse200 = {
  data: ProjectRolesEntity;
  status: 200;
};

export type usersProjectRolesResponseComposite = usersProjectRolesResponse200;

export type usersProjectRolesResponse = usersProjectRolesResponseComposite & {
  headers: Headers;
};

export const getUsersProjectRolesUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}/projects`;
};

export const usersProjectRoles = async (
  uid: string,
  options?: RequestInit,
): Promise<usersProjectRolesResponse> => {
  return customInstance<usersProjectRolesResponse>(
    getUsersProjectRolesUrl(uid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * User is updated with projects and roles
 * @summary Updates the projects and roles for user
 */
export type usersProjectRolesPutResponse204 = {
  data: void;
  status: 204;
};

export type usersProjectRolesPutResponseComposite =
  usersProjectRolesPutResponse204;

export type usersProjectRolesPutResponse =
  usersProjectRolesPutResponseComposite & {
    headers: Headers;
  };

export const getUsersProjectRolesPutUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}/projects`;
};

export const usersProjectRolesPut = async (
  uid: string,
  v1ProjectRolesPatchBody: V1ProjectRolesPatchBody,
  options?: RequestInit,
): Promise<usersProjectRolesPutResponse> => {
  return customInstance<usersProjectRolesPutResponse>(
    getUsersProjectRolesPutUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1ProjectRolesPatchBody),
    },
  );
};

/**
 * Returns resource roles for user
 * @summary Returns the specified individual and resource roles for a user
 */
export type usersUidResourceRolesResponse200 = {
  data: ResourceRoles;
  status: 200;
};

export type usersUidResourceRolesResponseComposite =
  usersUidResourceRolesResponse200;

export type usersUidResourceRolesResponse =
  usersUidResourceRolesResponseComposite & {
    headers: Headers;
  };

export const getUsersUidResourceRolesUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}/resourceRoles`;
};

export const usersUidResourceRoles = async (
  uid: string,
  options?: RequestInit,
): Promise<usersUidResourceRolesResponse> => {
  return customInstance<usersUidResourceRolesResponse>(
    getUsersUidResourceRolesUrl(uid),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Resource roles added to specific user
 * @summary Add resource roles for user
 */
export type usersUidResourceRolesCreateResponse204 = {
  data: void;
  status: 204;
};

export type usersUidResourceRolesCreateResponseComposite =
  usersUidResourceRolesCreateResponse204;

export type usersUidResourceRolesCreateResponse =
  usersUidResourceRolesCreateResponseComposite & {
    headers: Headers;
  };

export const getUsersUidResourceRolesCreateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}/resourceRoles`;
};

export const usersUidResourceRolesCreate = async (
  uid: string,
  v1ResourceRolesUpdateEntityBody: V1ResourceRolesUpdateEntityBody,
  options?: RequestInit,
): Promise<usersUidResourceRolesCreateResponse> => {
  return customInstance<usersUidResourceRolesCreateResponse>(
    getUsersUidResourceRolesCreateUrl(uid),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1ResourceRolesUpdateEntityBody),
    },
  );
};

/**
 * @summary Deleted the resource roles from user
 */
export type usersUidResourceRolesUidDeleteResponse204 = {
  data: void;
  status: 204;
};

export type usersUidResourceRolesUidDeleteResponseComposite =
  usersUidResourceRolesUidDeleteResponse204;

export type usersUidResourceRolesUidDeleteResponse =
  usersUidResourceRolesUidDeleteResponseComposite & {
    headers: Headers;
  };

export const getUsersUidResourceRolesUidDeleteUrl = (
  uid: string,
  resourceRoleUid: string,
) => {
  return `https://api.spectrocloud.com/v1/users/${uid}/resourceRoles/${resourceRoleUid}`;
};

export const usersUidResourceRolesUidDelete = async (
  uid: string,
  resourceRoleUid: string,
  options?: RequestInit,
): Promise<usersUidResourceRolesUidDeleteResponse> => {
  return customInstance<usersUidResourceRolesUidDeleteResponse>(
    getUsersUidResourceRolesUidDeleteUrl(uid, resourceRoleUid),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * Specific resource roles fo user is updated
 * @summary Updates the resource roles for user
 */
export type usersResourceRolesUidUpdateResponse204 = {
  data: void;
  status: 204;
};

export type usersResourceRolesUidUpdateResponseComposite =
  usersResourceRolesUidUpdateResponse204;

export type usersResourceRolesUidUpdateResponse =
  usersResourceRolesUidUpdateResponseComposite & {
    headers: Headers;
  };

export const getUsersResourceRolesUidUpdateUrl = (
  uid: string,
  resourceRoleUid: string,
) => {
  return `https://api.spectrocloud.com/v1/users/${uid}/resourceRoles/${resourceRoleUid}`;
};

export const usersResourceRolesUidUpdate = async (
  uid: string,
  resourceRoleUid: string,
  v1ResourceRolesUpdateEntityBody: V1ResourceRolesUpdateEntityBody,
  options?: RequestInit,
): Promise<usersResourceRolesUidUpdateResponse> => {
  return customInstance<usersResourceRolesUidUpdateResponse>(
    getUsersResourceRolesUidUpdateUrl(uid, resourceRoleUid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(v1ResourceRolesUpdateEntityBody),
    },
  );
};

/**
 * Returns roles clubbed from team
 * @summary Returns the specified individual and team roles for a user
 */
export type usersUidRolesResponse200 = {
  data: UserRolesEntity;
  status: 200;
};

export type usersUidRolesResponseComposite = usersUidRolesResponse200;

export type usersUidRolesResponse = usersUidRolesResponseComposite & {
  headers: Headers;
};

export const getUsersUidRolesUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}/roles`;
};

export const usersUidRoles = async (
  uid: string,
  options?: RequestInit,
): Promise<usersUidRolesResponse> => {
  return customInstance<usersUidRolesResponse>(getUsersUidRolesUrl(uid), {
    ...options,
    method: "GET",
  });
};

/**
 * User is updated with roles
 * @summary Updates the roles for user
 */
export type usersUidRolesUpdateResponse204 = {
  data: void;
  status: 204;
};

export type usersUidRolesUpdateResponseComposite =
  usersUidRolesUpdateResponse204;

export type usersUidRolesUpdateResponse =
  usersUidRolesUpdateResponseComposite & {
    headers: Headers;
  };

export const getUsersUidRolesUpdateUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}/roles`;
};

export const usersUidRolesUpdate = async (
  uid: string,
  userRoleUIDs: UserRoleUIDs,
  options?: RequestInit,
): Promise<usersUidRolesUpdateResponse> => {
  return customInstance<usersUidRolesUpdateResponse>(
    getUsersUidRolesUpdateUrl(uid),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userRoleUIDs),
    },
  );
};

/**
 * @summary Users status login mode
 */
export type usersStatusLoginModeResponse204 = {
  data: void;
  status: 204;
};

export type usersStatusLoginModeResponseComposite =
  usersStatusLoginModeResponse204;

export type usersStatusLoginModeResponse =
  usersStatusLoginModeResponseComposite & {
    headers: Headers;
  };

export const getUsersStatusLoginModeUrl = (uid: string) => {
  return `https://api.spectrocloud.com/v1/users/${uid}/status/loginMode`;
};

export const usersStatusLoginMode = async (
  uid: string,
  userStatusLoginMode: UserStatusLoginMode,
  options?: RequestInit,
): Promise<usersStatusLoginModeResponse> => {
  return customInstance<usersStatusLoginModeResponse>(
    getUsersStatusLoginModeUrl(uid),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userStatusLoginMode),
    },
  );
};
