name: CI
on:
  push:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-with-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "22"
          cache: "npm"

      - name: Setup Copywrite
        uses: hashicorp/setup-copywrite

      - name: Install dependencies
        run: make install-dependencies

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.SPECTRO_TOKEN }}
          USER: ${{ secrets.SPECTRO_USER }}
        run: git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Ensure Reviewable
        run: make check-diff

      - name: Generate
        run: make generate

      - name: Test
        run: make test
